namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Affliction : Warlock
    {
        public Spell AbsoluteCorruption = new Spell("Absolute Corruption", ClassType.Warlock, ClassSpec.Affliction, new[] { 196103 }, new[] { 0 }, 5, 1117878, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Agony = new Spell("Agony", ClassType.Warlock, ClassSpec.Affliction, new[] { 980, 231792 }, new[] { 10, 28 }, 0, 136139, new double[] { 0 }, new double[] { 18 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy) });
        public Spell Corruption = new Spell("Corruption", ClassType.Warlock, ClassSpec.Affliction, new[] { 317031, 334342 }, new[] { 14, 54 }, 0, 136118, new double[] { }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell CreepingDeath = new Spell("Creeping Death", ClassType.Warlock, ClassSpec.Affliction, new[] { 264000 }, new[] { 0 }, 20, 132095, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell DarkCaller = new Spell("Dark Caller", ClassType.Warlock, ClassSpec.Affliction, new[] { 334183 }, new[] { 0 }, 16, 538445, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell DarkSoulMisery = new Spell("Dark Soul: Misery", ClassType.Warlock, ClassSpec.Affliction, new[] { 113860 }, new[] { 0 }, 21, 463286, new double[] { 0 }, new double[] { 20 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.MeleeSlow) });
        public Spell DrainSoul = new Spell("Drain Soul", ClassType.Warlock, ClassSpec.Affliction, new[] { 198590 }, new[] { 0 }, 3, 136163, new double[] { 0 }, new double[] { 5 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Haunt = new Spell("Haunt", ClassType.Warlock, ClassSpec.Affliction, new[] { 48181 }, new[] { 18 }, 17, 236298, new double[] { 0 }, new double[] { 18 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.SchoolMaskDamageFromCaster), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell InevitableDemise = new Spell("Inevitable Demise", ClassType.Warlock, ClassSpec.Affliction, new[] { 334319 }, new[] { 1 }, 2, 537517, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MasteryPotentAfflictions = new Spell("Mastery: Potent Afflictions", ClassType.Warlock, ClassSpec.Affliction, new[] { 77215 }, new[] { 10 }, 0, 460699, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell Nightfall = new Spell("Nightfall", ClassType.Warlock, ClassSpec.Affliction, new[] { 108558 }, new[] { 0 }, 1, 136223, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SeedOfCorruption = new Spell("Seed of Corruption", ClassType.Warlock, ClassSpec.Affliction, new[] { 27243 }, new[] { 27 }, 0, 136193, new double[] { 0 }, new double[] { 12 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell ShadowEmbrace = new Spell("Shadow Embrace", ClassType.Warlock, ClassSpec.Affliction, new[] { 32388 }, new[] { 58 }, 0, 136198, new double[] { }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell SiphonLife = new Spell("Siphon Life", ClassType.Warlock, ClassSpec.Affliction, new[] { 63106 }, new[] { 1 }, 6, 136188, new double[] { 0 }, new double[] { 15 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicLeech) });
        public Spell Soulstone = new Spell("Soulstone", ClassType.Warlock, ClassSpec.Affliction, new[] { 231811 }, new[] { 48 }, 0, 136210, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SowTheSeeds = new Spell("Sow the Seeds", ClassType.Warlock, ClassSpec.Affliction, new[] { 196226 }, new[] { 0 }, 10, 136193, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SummonDarkglare = new Spell("Summon Darkglare", ClassType.Warlock, ClassSpec.Affliction, new[] { 205180 }, new[] { 42 }, 0, 1416161, new double[] { 0 }, new double[] { 20 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ScriptEffect, EffectAuraType.None), new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None) });
        public Spell UnstableAffliction = new Spell("Unstable Affliction", ClassType.Warlock, ClassSpec.Affliction, new[] { 231791, 316099, 334315 }, new[] { 13, 43, 56 }, 0, 136228, new double[] { 0 }, new double[] { 16 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell VileTaint = new Spell("Vile Taint", ClassType.Warlock, ClassSpec.Affliction, new[] { 278350 }, new[] { 0 }, 12, 1391774, new double[] { 0 }, new double[] { 10 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDecreaseSpeed), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage) });
        public Spell WritheInAgony = new Spell("Writhe in Agony", ClassType.Warlock, ClassSpec.Affliction, new[] { 196102 }, new[] { 0 }, 4, 136139, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
    }
}