namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Arcane : Mage
    {
        public Spell AlterTime = new Spell("Alter Time", ClassType.Mage, ClassSpec.Arcane, new[] { 342245 }, new[] { 19 }, 0, 609811, new double[] { 1 }, new double[] { 20 }, false, 0, new[] { "Alter Time" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell Amplification = new Spell("Amplification", ClassType.Mage, ClassSpec.Arcane, new[] { 236628 }, new[] { 0 }, 1, 429383, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell ArcaneBarrage = new Spell("Arcane Barrage", ClassType.Mage, ClassSpec.Arcane, new[] { 44425, 231564, 321526 }, new[] { 10, 31, 52 }, 0, 236205, new double[] { 3 }, new double[] { }, false, 40, new[] { "Arcane Barrage" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell ArcaneBlast = new Spell("Arcane Blast", ClassType.Mage, ClassSpec.Arcane, new[] { 30451 }, new[] { 10 }, 0, 135735, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell ArcaneEcho = new Spell("Arcane Echo", ClassType.Mage, ClassSpec.Arcane, new[] { 342231 }, new[] { 1 }, 11, 1041234, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ArcaneExplosion = new Spell("Arcane Explosion", ClassType.Mage, ClassSpec.Arcane, new[] { 321752 }, new[] { 18 }, 0, 136116, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell ArcaneFamiliar = new Spell("Arcane Familiar", ClassType.Mage, ClassSpec.Arcane, new[] { 205022 }, new[] { 1 }, 3, 1041232, new double[] { 0 }, new double[] { 3600 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell ArcaneMage = new Spell("Arcane Mage", ClassType.Mage, ClassSpec.Arcane, new[] { 137021 }, new[] { 10 }, 0, 236216, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, (EffectAuraType)429), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModPowerRegenPercent) });
        public Spell ArcaneMissiles = new Spell("Arcane Missiles", ClassType.Mage, ClassSpec.Arcane, new[] { 5143 }, new[] { 13 }, 0, 136096, new double[] { 0 }, new double[] { 2.5 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicTriggerSpell), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell ArcanePower = new Spell("Arcane Power", ClassType.Mage, ClassSpec.Arcane, new[] { 12042, 321739, 343208 }, new[] { 29, 41, 56 }, 0, 136048, new double[] { 0 }, new double[] { 10 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModPowerCostSchoolPct) });
        public Spell ChronoShift = new Spell("Chrono Shift", ClassType.Mage, ClassSpec.Arcane, new[] { 235711 }, new[] { 1 }, 13, 629533, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Clearcasting = new Spell("Clearcasting", ClassType.Mage, ClassSpec.Arcane, new[] { 79684, 321420, 321758 }, new[] { 14, 23, 32 }, 0, 136170, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModManaRegenFromStat), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell ConjureManaGem = new Spell("Conjure Mana Gem", ClassType.Mage, ClassSpec.Arcane, new[] { 759 }, new[] { 17 }, 0, 134132, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.CreateItem, EffectAuraType.None), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Enlightened = new Spell("Enlightened", ClassType.Mage, ClassSpec.Arcane, new[] { 321387 }, new[] { 0 }, 21, 1041231, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcOnPowerAmount) });
        public Spell Evocation = new Spell("Evocation", ClassType.Mage, ClassSpec.Arcane, new[] { 12051, 231565 }, new[] { 27, 43 }, 0, 136075, new double[] { 0 }, new double[] { 6 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ChargeRecoveryMultiplier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModPowerRegenPercent), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy) });
        public Spell GreaterInvisibility = new Spell("Greater Invisibility", ClassType.Mage, ClassSpec.Arcane, new[] { 110959 }, new[] { 47 }, 0, 575584, new double[] { 120 }, new double[] { }, false, 0, new[] { "Invisibility" }, new[] { new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell MasterOfTime = new Spell("Master of Time", ClassType.Mage, ClassSpec.Arcane, new[] { 342249 }, new[] { 0 }, 4, 2026009, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModManaRegenFromStat) });
        public Spell MasterySavant = new Spell("Mastery: Savant", ClassType.Mage, ClassSpec.Arcane, new[] { 190740 }, new[] { 10 }, 0, 135738, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, (EffectAuraType)178), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModManaRegenPct) });
        public Spell NetherTempest = new Spell("Nether Tempest", ClassType.Mage, ClassSpec.Arcane, new[] { 114923 }, new[] { 1 }, 12, 610471, new double[] { 0 }, new double[] { 12 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage) });
        public Spell PresenceOfMind = new Spell("Presence of Mind", ClassType.Mage, ClassSpec.Arcane, new[] { 205025, 321742 }, new[] { 42, 54 }, 0, 136031, new double[] { 0 }, new double[] { -0.001 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell PrismaticBarrier = new Spell("Prismatic Barrier", ClassType.Mage, ClassSpec.Arcane, new[] { 235450, 321745 }, new[] { 11, 48 }, 0, 135991, new double[] { 0 }, new double[] { 60 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAuraDurationByDispel), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.SchoolAbsorb) });
        public Spell Resonance = new Spell("Resonance", ClassType.Mage, ClassSpec.Arcane, new[] { 205028 }, new[] { 1 }, 10, 135728, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Reverberate = new Spell("Reverberate", ClassType.Mage, ClassSpec.Arcane, new[] { 281482 }, new[] { 1 }, 16, 135731, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell RuleOfThrees = new Spell("Rule of Threes", ClassType.Mage, ClassSpec.Arcane, new[] { 264354 }, new[] { 0 }, 2, 135753, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Slipstream = new Spell("Slipstream", ClassType.Mage, ClassSpec.Arcane, new[] { 236457 }, new[] { 1 }, 6, 135933, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.CastWhileWalking) });
        public Spell Slow = new Spell("Slow", ClassType.Mage, ClassSpec.Arcane, new[] { 31589, 321747 }, new[] { 12, 38 }, 0, 136091, new double[] { 0 }, new double[] { 15 }, false, 35, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDecreaseSpeed) });
        public Spell Supernova = new Spell("Supernova", ClassType.Mage, ClassSpec.Arcane, new[] { 157980 }, new[] { 1 }, 18, 1033912, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.KnockBackDest, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell TimeAnomaly = new Spell("Time Anomaly", ClassType.Mage, ClassSpec.Arcane, new[] { 210805 }, new[] { 0 }, 20, 458224, new double[] { }, new double[] { }, true, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy) });
        public Spell TouchOfTheMagi = new Spell("Touch of the Magi", ClassType.Mage, ClassSpec.Arcane, new[] { 321507, 343215 }, new[] { 33, 46 }, 0, 1033909, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
    }
}