namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Arms : Warrior
    {
        public Spell AngerManagement = new Spell("Anger Management", ClassType.Warrior, ClassSpec.Arms, new[] { 152278 }, new[] { 0 }, 19, 971080, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Avatar = new Spell("Avatar", ClassType.Warrior, ClassSpec.Arms, new[] { 107574 }, new[] { 32 }, 17, 613534, new double[] { 0 }, new double[] { 20 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAutoattackDamage), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModScale), new SpellEffectData(SpellEffectName.ApplyAuraOnPet, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.ScriptEffect, EffectAuraType.None) });
        public Spell Bladestorm = new Spell("Bladestorm", ClassType.Warrior, ClassSpec.Arms, new[] { 227847 }, new[] { 38 }, 0, 236303, new double[] { 0 }, new double[] { 6 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AllowOnlyAbility), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.MechanicImmunityMask), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicTriggerSpell) });
        public Spell Cleave = new Spell("Cleave", ClassType.Warrior, ClassSpec.Arms, new[] { 845 }, new[] { 0 }, 15, 132338, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell CollateralDamage = new Spell("Collateral Damage", ClassType.Warrior, ClassSpec.Arms, new[] { 334779 }, new[] { 0 }, 13, 236309, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ColossusSmash = new Spell("Colossus Smash", ClassType.Warrior, ClassSpec.Arms, new[] { 167105, 316411 }, new[] { 19, 37 }, 0, 464973, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell DeadlyCalm = new Spell("Deadly Calm", ClassType.Warrior, ClassSpec.Arms, new[] { 262228 }, new[] { 0 }, 18, 298660, new double[] { 0 }, new double[] { 20 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAdditionalPowerCost) });
        public Spell DefensiveStance = new Spell("Defensive Stance", ClassType.Warrior, ClassSpec.Arms, new[] { 197690 }, new[] { 0 }, 12, 132341, new double[] { 6 }, new double[] { -0.001 }, false, 0, new[] { "Class - Warrior - Defensive Stance" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentDone), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.OverrideActionbarSpells) });
        public Spell DieByTheSword = new Spell("Die by the Sword", ClassType.Warrior, ClassSpec.Arms, new[] { 118038, 315948 }, new[] { 23, 52 }, 0, 132336, new double[] { 0 }, new double[] { 8 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAttackerSpellAndWeaponCritChance), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModParryPercent) });
        public Spell Dreadnaught = new Spell("Dreadnaught", ClassType.Warrior, ClassSpec.Arms, new[] { 262150 }, new[] { 0 }, 20, 135275, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxCharges) });
        public Spell Execute = new Spell("Execute", ClassType.Warrior, ClassSpec.Arms, new[] { 231830, 316405 }, new[] { 13, 18 }, 0, 135358, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell FervorOfBattle = new Spell("Fervor of Battle", ClassType.Warrior, ClassSpec.Arms, new[] { 202316 }, new[] { 0 }, 8, 236286, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ImpendingVictory = new Spell("Impending Victory", ClassType.Warrior, ClassSpec.Arms, new[] { 202168 }, new[] { 0 }, 5, 589768, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell InForTheKill = new Spell("In For The Kill", ClassType.Warrior, ClassSpec.Arms, new[] { 248621 }, new[] { 1 }, 16, 1029718, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Massacre = new Spell("Massacre", ClassType.Warrior, ClassSpec.Arms, new[] { 281001 }, new[] { 0 }, 7, 135358, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.OverrideActionbarSpells) });
        public Spell MasteryDeepWounds = new Spell("Mastery: Deep Wounds", ClassType.Warrior, ClassSpec.Arms, new[] { 262111 }, new[] { 10 }, 0, 132090, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell MortalStrike = new Spell("Mortal Strike", ClassType.Warrior, ClassSpec.Arms, new[] { 12294, 261900 }, new[] { 10, 44 }, 0, 132355, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Overpower = new Spell("Overpower", ClassType.Warrior, ClassSpec.Arms, new[] { 7384, 316440, 316441 }, new[] { 12, 28, 49 }, 0, 132223, new double[] { 0 }, new double[] { 15 }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell PiercingHowl = new Spell("Piercing Howl", ClassType.Warrior, ClassSpec.Arms, new[] { 12323 }, new[] { 21 }, 0, 136147, new double[] { 0 }, new double[] { 8 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDecreaseSpeed) });
        public Spell Ravager = new Spell("Ravager", ClassType.Warrior, ClassSpec.Arms, new[] { 152277 }, new[] { 0 }, 21, 970854, new double[] { 0 }, new double[] { 12 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Rend = new Spell("Rend", ClassType.Warrior, ClassSpec.Arms, new[] { 772 }, new[] { 1 }, 9, 132155, new double[] { 0 }, new double[] { 15 }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, (EffectAuraType)501), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell SeasonedSoldier = new Spell("Seasoned Soldier", ClassType.Warrior, ClassSpec.Arms, new[] { 279423 }, new[] { 27 }, 0, 132400, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SecondWind = new Spell("Second Wind", ClassType.Warrior, ClassSpec.Arms, new[] { 29838 }, new[] { 1 }, 10, 132175, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Skullsplitter = new Spell("Skullsplitter", ClassType.Warrior, ClassSpec.Arms, new[] { 260643 }, new[] { 1 }, 3, 2065621, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Slam = new Spell("Slam", ClassType.Warrior, ClassSpec.Arms, new[] { 261901, 316534 }, new[] { 20, 48 }, 0, 132340, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell StormBolt = new Spell("Storm Bolt", ClassType.Warrior, ClassSpec.Arms, new[] { 107570 }, new[] { 0 }, 6, 613535, new double[] { 0 }, new double[] { }, false, 20, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell SuddenDeath = new Spell("Sudden Death", ClassType.Warrior, ClassSpec.Arms, new[] { 29725 }, new[] { 0 }, 2, 132346, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SweepingStrikes = new Spell("Sweeping Strikes", ClassType.Warrior, ClassSpec.Arms, new[] { 260708, 316432, 316433 }, new[] { 22, 42, 58 }, 0, 132306, new double[] { 0 }, new double[] { 12 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Tactician = new Spell("Tactician", ClassType.Warrior, ClassSpec.Arms, new[] { 184783 }, new[] { 32 }, 0, 236317, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell WarMachine = new Spell("War Machine", ClassType.Warrior, ClassSpec.Arms, new[] { 262231 }, new[] { 0 }, 1, 132205, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModRageFromDamageDealt), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Warbreaker = new Spell("Warbreaker", ClassType.Warrior, ClassSpec.Arms, new[] { 262161 }, new[] { 0 }, 14, 2065633, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
    }
}