namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Assassination : Rogue
    {
        public Spell Alacrity = new Spell("Alacrity", ClassType.Rogue, ClassSpec.Assassination, new[] { 193539 }, new[] { 0 }, 17, 571558, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Blindside = new Spell("Blindside", ClassType.Rogue, ClassSpec.Assassination, new[] { 328085 }, new[] { 0 }, 3, 236274, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell CrimsonTempest = new Spell("Crimson Tempest", ClassType.Rogue, ClassSpec.Assassination, new[] { 121411 }, new[] { 25 }, 21, 464079, new double[] { 0 }, new double[] { 2 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell DeadlyPoison = new Spell("Deadly Poison", ClassType.Rogue, ClassSpec.Assassination, new[] { 2823 }, new[] { 13 }, 0, 132290, new double[] { }, new double[] { 3600 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Envenom = new Spell("Envenom", ClassType.Rogue, ClassSpec.Assassination, new[] { 32645 }, new[] { 22 }, 0, 132287, new double[] { 0 }, new double[] { 1 }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Exsanguinate = new Spell("Exsanguinate", ClassType.Rogue, ClassSpec.Assassination, new[] { 200806 }, new[] { 0 }, 18, 538040, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell FanOfKnives = new Spell("Fan of Knives", ClassType.Rogue, ClassSpec.Assassination, new[] { 51723 }, new[] { 19 }, 0, 236273, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Garrote = new Spell("Garrote", ClassType.Rogue, ClassSpec.Assassination, new[] { 703, 231719 }, new[] { 16, 46 }, 0, 132297, new double[] { 0 }, new double[] { 18 }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModSpellDamageFromCaster), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None) });
        public Spell HiddenBlades = new Spell("Hidden Blades", ClassType.Rogue, ClassSpec.Assassination, new[] { 270061 }, new[] { 0 }, 20, 236273, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy) });
        public Spell ImprovedPoisons = new Spell("Improved Poisons", ClassType.Rogue, ClassSpec.Assassination, new[] { 14117, 330542 }, new[] { 43, 52 }, 0, 132273, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell IronWire = new Spell("Iron Wire", ClassType.Rogue, ClassSpec.Assassination, new[] { 196861 }, new[] { 0 }, 14, 133243, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell LeechingPoison = new Spell("Leeching Poison", ClassType.Rogue, ClassSpec.Assassination, new[] { 280716 }, new[] { 0 }, 10, 538440, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MasterAssassin = new Spell("Master Assassin", ClassType.Rogue, ClassSpec.Assassination, new[] { 255989 }, new[] { 0 }, 6, 132109, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MasterPoisoner = new Spell("Master Poisoner", ClassType.Rogue, ClassSpec.Assassination, new[] { 196864 }, new[] { 0 }, 1, 132108, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell MasteryPotentAssassin = new Spell("Mastery: Potent Assassin", ClassType.Rogue, ClassSpec.Assassination, new[] { 76803, 319473 }, new[] { 10, 41 }, 0, 236270, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Mutilate = new Spell("Mutilate", ClassType.Rogue, ClassSpec.Assassination, new[] { 1329 }, new[] { 12 }, 0, 132304, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell PoisonBomb = new Spell("Poison Bomb", ClassType.Rogue, ClassSpec.Assassination, new[] { 255544 }, new[] { 0 }, 19, 538441, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell PoisonedKnife = new Spell("Poisoned Knife", ClassType.Rogue, ClassSpec.Assassination, new[] { 185565 }, new[] { 29 }, 0, 1373909, new double[] { 0 }, new double[] { }, false, 30, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Rupture = new Spell("Rupture", ClassType.Rogue, ClassSpec.Assassination, new[] { 1943 }, new[] { 17 }, 0, 132302, new double[] { 0 }, new double[] { 4 }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell SealFate = new Spell("Seal Fate", ClassType.Rogue, ClassSpec.Assassination, new[] { 14190 }, new[] { 27 }, 0, 236281, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Shadowstep = new Spell("Shadowstep", ClassType.Rogue, ClassSpec.Assassination, new[] { 36554 }, new[] { 18 }, 0, 132303, new double[] { 0 }, new double[] { 2 }, false, 25, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModIncreaseSpeed), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell Shiv = new Spell("Shiv", ClassType.Rogue, ClassSpec.Assassination, new[] { 319032 }, new[] { 58 }, 0, 135428, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SinisterStrike = new Spell("Sinister Strike", ClassType.Rogue, ClassSpec.Assassination, new[] { 279877 }, new[] { 12 }, 0, 136189, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell SliceAndDice = new Spell("Slice and Dice", ClassType.Rogue, ClassSpec.Assassination, new[] { 344362 }, new[] { 56 }, 0, 132306, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell Vendetta = new Spell("Vendetta", ClassType.Rogue, ClassSpec.Assassination, new[] { 79140 }, new[] { 42 }, 0, 458726, new double[] { 0 }, new double[] { 20 }, false, 30, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMeleeDamageFromCaster), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModSpellDamageFromCaster), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModStalked), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell VenomousWounds = new Spell("Venomous Wounds", ClassType.Rogue, ClassSpec.Assassination, new[] { 79134 }, new[] { 37 }, 0, 458736, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell WoundPoison = new Spell("Wound Poison", ClassType.Rogue, ClassSpec.Assassination, new[] { 319066 }, new[] { 44 }, 0, 134197, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });

        // Internal Bleeding - Internal Bleeding 154953
        public Spell InternalBleeding = new Spell("Internal Bleeding", ClassType.Rogue, ClassSpec.Assassination, 154953, 13);
    }
}