namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Demonology : Warlock
    {
        public Spell BilescourgeBombers = new Spell("Bilescourge Bombers", ClassType.Warlock, ClassSpec.Demonology, new[] { 267211 }, new[] { 1 }, 2, 132182, new double[] { 0 }, new double[] { 6 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.CreateAreaTrigger, EffectAuraType.None) });
        public Spell CallDreadstalkers = new Spell("Call Dreadstalkers", ClassType.Warlock, ClassSpec.Demonology, new[] { 104316, 334727 }, new[] { 13, 54 }, 0, 1378282, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Demonbolt = new Spell("Demonbolt", ClassType.Warlock, ClassSpec.Demonology, new[] { 264178 }, new[] { 14 }, 0, 2032588, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell DemonicCalling = new Spell("Demonic Calling", ClassType.Warlock, ClassSpec.Demonology, new[] { 205145 }, new[] { 0 }, 4, 460856, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Doom = new Spell("Doom", ClassType.Warlock, ClassSpec.Demonology, new[] { 603 }, new[] { 15 }, 6, 136122, new double[] { 0 }, new double[] { 20 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage) });
        public Spell Dreadlash = new Spell("Dreadlash", ClassType.Warlock, ClassSpec.Demonology, new[] { 264078 }, new[] { 10 }, 1, 136221, new double[] { }, new double[] { }, false, 40, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell FelFirebolt = new Spell("Fel Firebolt", ClassType.Warlock, ClassSpec.Demonology, new[] { 334591 }, new[] { 56 }, 0, 136218, new double[] { }, new double[] { }, false, 40, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell FromTheShadows = new Spell("From the Shadows", ClassType.Warlock, ClassSpec.Demonology, new[] { 267170 }, new[] { 10 }, 10, 1378282, new double[] { }, new double[] { }, false, 40, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell GrimoireFelguard = new Spell("Grimoire: Felguard", ClassType.Warlock, ClassSpec.Demonology, new[] { 111898 }, new[] { 1 }, 18, 136216, new double[] { 120 }, new double[] { 17 }, false, 40, new[] { "Warlock - Grimoire of Service" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None) });
        public Spell Implosion = new Spell("Implosion", ClassType.Warlock, ClassSpec.Demonology, new[] { 196277 }, new[] { 27 }, 0, 2065588, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell MasteryMasterDemonologist = new Spell("Mastery: Master Demonologist", ClassType.Warlock, ClassSpec.Demonology, new[] { 77219 }, new[] { 10 }, 0, 136203, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, (EffectAuraType)429), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell SoulConduit = new Spell("Soul Conduit", ClassType.Warlock, ClassSpec.Demonology, new[] { 215941 }, new[] { 0 }, 16, 136213, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SoulStrike = new Spell("Soul Strike", ClassType.Warlock, ClassSpec.Demonology, new[] { 264057 }, new[] { 1 }, 11, 1452864, new double[] { 0 }, new double[] { }, false, 50, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Soulstone = new Spell("Soulstone", ClassType.Warlock, ClassSpec.Demonology, new[] { 231811 }, new[] { 48 }, 0, 136210, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SummonDemonicTyrant = new Spell("Summon Demonic Tyrant", ClassType.Warlock, ClassSpec.Demonology, new[] { 265187, 334585 }, new[] { 42, 58 }, 0, 2065628, new double[] { 0 }, new double[] { 15 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None) });
        public Spell SummonFelguard = new Spell("Summon Felguard", ClassType.Warlock, ClassSpec.Demonology, new[] { 30146 }, new[] { 12 }, 0, 136216, new double[] { 0 }, new double[] { -0.001 }, false, 0, new[] { "Warlock - Summon Demon" }, new[] { new SpellEffectData(SpellEffectName.SummonPet, EffectAuraType.None) });
        public Spell SummonVilefiend = new Spell("Summon Vilefiend", ClassType.Warlock, ClassSpec.Demonology, new[] { 264119 }, new[] { 1 }, 12, 1616211, new double[] { 0 }, new double[] { 15 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None) });
    }
}