namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class DemonHunter
    {
        public Spell AbyssalStrike = new Spell("Abyssal Strike", ClassType.DemonHunter, ClassSpec.Base, new[] { 204841 }, new[] { 1 }, 0, 615096, new double[] { }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None) });
        public Spell AgonizingFlames = new Spell("Agonizing Flames", ClassType.DemonHunter, ClassSpec.Base, new[] { 209252 }, new[] { 1 }, 0, 574795, new double[] { }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None) });
        public Spell BladeTurning = new Spell("Blade Turning", ClassType.DemonHunter, ClassSpec.Base, new[] { 203753, 247254 }, new[] { 1 }, 0, 456578, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Brooding = new Spell("Brooding", ClassType.DemonHunter, ClassSpec.Base, new[] { 222005 }, new[] { 50 }, 0, 135561, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell ChaosBrand = new Spell("Chaos Brand", ClassType.DemonHunter, ClassSpec.Base, new[] { 255260 }, new[] { 49 }, 0, 1450142, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ConsumeMagic = new Spell("Consume Magic", ClassType.DemonHunter, ClassSpec.Base, new[] { 278326, 320313, 338834 }, new[] { 17, 18, 37 }, 0, 828455, new double[] { 0 }, new double[] { }, false, 30, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dispel, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None) });
        public Spell DemonSpikes = new Spell("Demon Spikes", ClassType.DemonHunter, ClassSpec.Base, new[] { 203819 }, new[] { 1 }, 0, 1344645, new double[] { }, new double[] { 6 }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, (EffectAuraType)268), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentDone), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModParryPercent) });
        public Spell DemonicInfusion = new Spell("Demonic Infusion", ClassType.DemonHunter, ClassSpec.Base, new[] { 236189 }, new[] { 1 }, 0, 463284, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None) });
        public Spell DemonicWards = new Spell("Demonic Wards", ClassType.DemonHunter, ClassSpec.Base, new[] { 278386 }, new[] { 13 }, 0, 1266395, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken) });
        public Spell Disrupt = new Spell("Disrupt", ClassType.DemonHunter, ClassSpec.Base, new[] { 183752, 183782, 320361 }, new[] { 29, 46 }, 0, 1305153, new double[] { 15 }, new double[] { 3 }, false, 5, new[] { "Silence" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell), new SpellEffectData(SpellEffectName.InterruptCast, EffectAuraType.None) });
        public Spell EyeOfLeotheras = new Spell("Eye of Leotheras", ClassType.DemonHunter, ClassSpec.Base, new[] { 206649 }, new[] { 1 }, 0, 1380366, new double[] { 0 }, new double[] { 6 }, true, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Felblade = new Spell("Felblade", ClassType.DemonHunter, ClassSpec.Base, new[] { 213243 }, new[] { 50 }, 0, 1344646, new double[] { }, new double[] { }, false, 15, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell ImmolationAura = new Spell("Immolation Aura", ClassType.DemonHunter, ClassSpec.Base, new[] { 258920, 320364 }, new[] { 14, 18 }, 0, 1344649, new double[] { 0 }, new double[] { 6 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModRatingFromStat), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModResistancePct), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModSpeedAlways), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicTriggerSpell), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None) });
        public Spell Imprison = new Spell("Imprison", ClassType.DemonHunter, ClassSpec.Base, new[] { 217832, 332544 }, new[] { 34 }, 0, 1380368, new double[] { 0 }, new double[] { -0.001, 60 }, false, 20, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModCharm), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModStun) });
        public Spell Sever = new Spell("Sever", ClassType.DemonHunter, ClassSpec.Base, new[] { 235964 }, new[] { 1 }, 0, 1380369, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell SigilOfMisery = new Spell("Sigil of Misery", ClassType.DemonHunter, ClassSpec.Base, new[] { 202140 }, new[] { 1 }, 0, 1418287, new double[] { 180 }, new double[] { 2 }, false, 0, new[] { "Demon Hunter - Sigil of Misery" }, new[] { new SpellEffectData(SpellEffectName.CreateAreaTrigger, EffectAuraType.None) });
        public Spell SpectralSight = new Spell("Spectral Sight", ClassType.DemonHunter, ClassSpec.Base, new[] { 320379 }, new[] { 42 }, 0, 1247266, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell ThrowGlaive = new Spell("Throw Glaive", ClassType.DemonHunter, ClassSpec.Base, new[] { 185123, 320386 }, new[] { 19 }, 0, 1305159, new double[] { 0 }, new double[] { }, false, 30, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell Torment = new Spell("Torment", ClassType.DemonHunter, ClassSpec.Base, new[] { 185245 }, new[] { 9 }, 0, 1344654, new double[] { 8 }, new double[] { 3 }, false, 30, new[] { "Taunt/Detaunt" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModTaunt), new SpellEffectData(SpellEffectName.AttackMe, EffectAuraType.None) });

        public Spell SoulFragments = new Spell("Soul Fragments", ClassType.DemonHunter, ClassSpec.Base, 203981, 0, SpellType.BuffOnPlayer);
        public Spell Glide = new Spell("Glide", ClassType.DemonHunter, ClassSpec.Base, 131347, 0, SpellType.BuffOnPlayer);
    }
}