namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Destruction : Warlock
    {
        public Spell Backdraft = new Spell("Backdraft", ClassType.Warlock, ClassSpec.Destruction, new[] { 196406 }, new[] { 14 }, 0, 236290, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Cataclysm = new Spell("Cataclysm", ClassType.Warlock, ClassSpec.Destruction, new[] { 152108 }, new[] { 0 }, 12, 409545, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell ChannelDemonfire = new Spell("Channel Demonfire", ClassType.Warlock, ClassSpec.Destruction, new[] { 196447 }, new[] { 0 }, 20, 840407, new double[] { 0 }, new double[] { 3 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy) });
        public Spell ChaosBolt = new Spell("Chaos Bolt", ClassType.Warlock, ClassSpec.Destruction, new[] { 116858 }, new[] { 10 }, 0, 236291, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.EnergizePct, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Conflagrate = new Spell("Conflagrate", ClassType.Warlock, ClassSpec.Destruction, new[] { 17962, 231793 }, new[] { 13, 23 }, 0, 135807, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxCharges), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell DarkSoulInstability = new Spell("Dark Soul: Instability", ClassType.Warlock, ClassSpec.Destruction, new[] { 113858 }, new[] { 0 }, 21, 463286, new double[] { 0 }, new double[] { 20 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModCritPct) });
        public Spell Eradication = new Spell("Eradication", ClassType.Warlock, ClassSpec.Destruction, new[] { 196412 }, new[] { 0 }, 2, 236295, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell FireAndBrimstone = new Spell("Fire and Brimstone", ClassType.Warlock, ClassSpec.Destruction, new[] { 196408 }, new[] { 0 }, 11, 236297, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.HasteRanged) });
        public Spell Flashover = new Spell("Flashover", ClassType.Warlock, ClassSpec.Destruction, new[] { 267115 }, new[] { 0 }, 1, 236290, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell Havoc = new Spell("Havoc", ClassType.Warlock, ClassSpec.Destruction, new[] { 80240, 335174 }, new[] { 27, 54 }, 0, 460695, new double[] { 0 }, new double[] { 10 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Immolate = new Spell("Immolate", ClassType.Warlock, ClassSpec.Destruction, new[] { 348 }, new[] { 11 }, 0, 135817, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Incinerate = new Spell("Incinerate", ClassType.Warlock, ClassSpec.Destruction, new[] { 29722 }, new[] { 10 }, 0, 135789, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Inferno = new Spell("Inferno", ClassType.Warlock, ClassSpec.Destruction, new[] { 270545 }, new[] { 0 }, 10, 136186, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell InternalCombustion = new Spell("Internal Combustion", ClassType.Warlock, ClassSpec.Destruction, new[] { 266134 }, new[] { 0 }, 5, 236220, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MasteryChaoticEnergies = new Spell("Mastery: Chaotic Energies", ClassType.Warlock, ClassSpec.Destruction, new[] { 77220 }, new[] { 10 }, 0, 135799, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.SchoolAbsorb) });
        public Spell RainOfChaos = new Spell("Rain of Chaos", ClassType.Warlock, ClassSpec.Destruction, new[] { 266086 }, new[] { 0 }, 17, 135804, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell RainOfFire = new Spell("Rain of Fire", ClassType.Warlock, ClassSpec.Destruction, new[] { 5740, 335189 }, new[] { 28, 56 }, 0, 136186, new double[] { 0 }, new double[] { 8 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.CreateAreaTrigger, EffectAuraType.None), new SpellEffectData(SpellEffectName.PersistentAreaAura, EffectAuraType.Dummy) });
        public Spell ReverseEntropy = new Spell("Reverse Entropy", ClassType.Warlock, ClassSpec.Destruction, new[] { 205148 }, new[] { 0 }, 4, 840406, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell RoaringBlaze = new Spell("Roaring Blaze", ClassType.Warlock, ClassSpec.Destruction, new[] { 205184 }, new[] { 0 }, 16, 460698, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Shadowburn = new Spell("Shadowburn", ClassType.Warlock, ClassSpec.Destruction, new[] { 17877 }, new[] { 1 }, 6, 136191, new double[] { 0 }, new double[] { 5 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell SoulFire = new Spell("Soul Fire", ClassType.Warlock, ClassSpec.Destruction, new[] { 6353 }, new[] { 0 }, 3, 135809, new double[] { 0 }, new double[] { }, false, 40, new[] { "Soul Fire" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Soulstone = new Spell("Soulstone", ClassType.Warlock, ClassSpec.Destruction, new[] { 231811 }, new[] { 48 }, 0, 136210, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SummonInfernal = new Spell("Summon Infernal", ClassType.Warlock, ClassSpec.Destruction, new[] { 1122, 335175 }, new[] { 42, 58 }, 0, 136219, new double[] { 180 }, new double[] { 0.25 }, false, 40, new[] { "Warlock - Summon Guardian" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerMissile, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerMissileSpellWithValue, EffectAuraType.None) });

        public Spell GrimoireSacrifice = new Spell("Grimoire of Sacrifice", ClassType.Warlock, ClassSpec.Destruction, 108503, 18);
    }
}