namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Discipline : Priest
    {
        public Spell Atonement = new Spell("Atonement", ClassType.Priest, ClassSpec.Discipline, new[] { 81749 }, new[] { 12 }, 0, 458720, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell DominantMind = new Spell("Dominant Mind", ClassType.Priest, ClassSpec.Discipline, new[] { 205367 }, new[] { 0 }, 11, 1386549, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.OverrideActionbarSpells) });
        public Spell Evangelism = new Spell("Evangelism", ClassType.Priest, ClassSpec.Discipline, new[] { 246287 }, new[] { 0 }, 21, 135895, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ScriptEffect, EffectAuraType.None) });
        public Spell FocusedWill = new Spell("Focused Will", ClassType.Priest, ClassSpec.Discipline, new[] { 285485 }, new[] { 43 }, 0, 458227, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell HolyNova = new Spell("Holy Nova", ClassType.Priest, ClassSpec.Discipline, new[] { 132157, 322112 }, new[] { 31, 56 }, 0, 135922, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData((SpellEffectName)0, EffectAuraType.None), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell Lenience = new Spell("Lenience", ClassType.Priest, ClassSpec.Discipline, new[] { 238063 }, new[] { 0 }, 19, 458720, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell Masochism = new Spell("Masochism", ClassType.Priest, ClassSpec.Discipline, new[] { 193063 }, new[] { 0 }, 5, 136176, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MasteryGrace = new Spell("Mastery: Grace", ClassType.Priest, ClassSpec.Discipline, new[] { 271534 }, new[] { 10 }, 0, 237543, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MindBlast = new Spell("Mind Blast", ClassType.Priest, ClassSpec.Discipline, new[] { 231682 }, new[] { 18 }, 0, 136224, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MindSear = new Spell("Mind Sear", ClassType.Priest, ClassSpec.Discipline, new[] { 48045 }, new[] { 26 }, 0, 237565, new double[] { 0 }, new double[] { 4.5 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicTriggerSpell), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell PainSuppression = new Spell("Pain Suppression", ClassType.Priest, ClassSpec.Discipline, new[] { 33206 }, new[] { 38 }, 0, 135936, new double[] { 0 }, new double[] { 8 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy) });
        public Spell Penance = new Spell("Penance", ClassType.Priest, ClassSpec.Discipline, new[] { 47540 }, new[] { 11 }, 0, 237545, new double[] { 9 }, new double[] { }, false, 40, new[] { "Class - Priest - Penance" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell PowerOfTheDarkSide = new Spell("Power of the Dark Side", ClassType.Priest, ClassSpec.Discipline, new[] { 198068 }, new[] { 47 }, 0, 1394892, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell PowerWordBarrier = new Spell("Power Word: Barrier", ClassType.Priest, ClassSpec.Discipline, new[] { 62618 }, new[] { 44 }, 0, 253400, new double[] { 0 }, new double[] { 10 }, false, 40, new[] { "Power Word: Barrier" }, new[] { new SpellEffectData(SpellEffectName.CreateAreaTrigger, EffectAuraType.None) });
        public Spell PowerWordRadiance = new Spell("Power Word: Radiance", ClassType.Priest, ClassSpec.Discipline, new[] { 194509, 322115 }, new[] { 23, 39 }, 0, 1386546, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxCharges), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None) });
        public Spell PsychicVoice = new Spell("Psychic Voice", ClassType.Priest, ClassSpec.Discipline, new[] { 196704 }, new[] { 0 }, 10, 132339, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell PurgeTheWicked = new Spell("Purge the Wicked", ClassType.Priest, ClassSpec.Discipline, new[] { 204197 }, new[] { 1 }, 16, 236216, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell Purify = new Spell("Purify", ClassType.Priest, ClassSpec.Discipline, new[] { 527 }, new[] { 18 }, 0, 135894, new double[] { 8 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dispel, EffectAuraType.None) });
        public Spell Rapture = new Spell("Rapture", ClassType.Priest, ClassSpec.Discipline, new[] { 47536 }, new[] { 41 }, 0, 237548, new double[] { 0 }, new double[] { 8 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDispelResist), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.WaterWalk), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Schism = new Spell("Schism", ClassType.Priest, ClassSpec.Discipline, new[] { 214621 }, new[] { 1 }, 3, 463285, new double[] { 0 }, new double[] { 9 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModSpellDamageFromCaster), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell ShadowMend = new Spell("Shadow Mend", ClassType.Priest, ClassSpec.Discipline, new[] { 186263, 186440 }, new[] { 1, 19 }, 0, 136202, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None) });
        public Spell Shadowfiend = new Spell("Shadowfiend", ClassType.Priest, ClassSpec.Discipline, new[] { 34433, 343726 }, new[] { 20, 32 }, 0, 136199, new double[] { 180 }, new double[] { 15 }, false, 40, new[] { "Priest - Shadowfiend" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell SinsOfTheMany = new Spell("Sins of the Many", ClassType.Priest, ClassSpec.Discipline, new[] { 280391 }, new[] { 0 }, 13, 135921, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Smite = new Spell("Smite", ClassType.Priest, ClassSpec.Discipline, new[] { 262861 }, new[] { 13 }, 0, 135924, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell TwistOfFate = new Spell("Twist of Fate", ClassType.Priest, ClassSpec.Discipline, new[] { 265259 }, new[] { 0 }, 2, 237566, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
    }
}