namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Elemental : Shaman
    {
        public Spell Aftershock = new Spell("Aftershock", ClassType.Shaman, ClassSpec.Elemental, new[] { 273221 }, new[] { 0 }, 4, 136099, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell AncestralGuidance = new Spell("Ancestral Guidance", ClassType.Shaman, ClassSpec.Elemental, new[] { 108281 }, new[] { 0 }, 14, 538564, new double[] { 0 }, new double[] { 10 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy) });
        public Spell Ascendance = new Spell("Ascendance", ClassType.Shaman, ClassSpec.Elemental, new[] { 114050 }, new[] { 50 }, 21, 135791, new double[] { 0 }, new double[] { 15 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ChargeRecoveryMod), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.OverrideActionbarSpells), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Transform) });
        public Spell ChainLightning = new Spell("Chain Lightning", ClassType.Shaman, ClassSpec.Elemental, new[] { 231722 }, new[] { 43 }, 0, 136015, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell CleanseSpirit = new Spell("Cleanse Spirit", ClassType.Shaman, ClassSpec.Elemental, new[] { 51886 }, new[] { 18 }, 0, 236288, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dispel, EffectAuraType.None) });
        public Spell EarthShield = new Spell("Earth Shield", ClassType.Shaman, ClassSpec.Elemental, new[] { 974 }, new[] { 22 }, 8, 136089, new double[] { 0 }, new double[] { 600 }, false, 40, new[] { "Earth Shield" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModHealingReceived) });
        public Spell EarthShock = new Spell("Earth Shock", ClassType.Shaman, ClassSpec.Elemental, new[] { 8042 }, new[] { 10 }, 0, 136026, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell EarthenRage = new Spell("Earthen Rage", ClassType.Shaman, ClassSpec.Elemental, new[] { 170374 }, new[] { 1 }, 1, 1016245, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Earthquake = new Spell("Earthquake", ClassType.Shaman, ClassSpec.Elemental, new[] { 61882 }, new[] { 38 }, 0, 451165, new double[] { 0 }, new double[] { 6 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.CreateAreaTrigger, EffectAuraType.None), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell EchoOfTheElements = new Spell("Echo of the Elements", ClassType.Shaman, ClassSpec.Elemental, new[] { 333919 }, new[] { 0 }, 2, 538566, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxCharges) });
        public Spell EchoingShock = new Spell("Echoing Shock", ClassType.Shaman, ClassSpec.Elemental, new[] { 320125 }, new[] { 10 }, 5, 1603013, new double[] { 0 }, new double[] { 8 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell ElementalBlast = new Spell("Elemental Blast", ClassType.Shaman, ClassSpec.Elemental, new[] { 117014 }, new[] { 0 }, 6, 651244, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell ElementalFury = new Spell("Elemental Fury", ClassType.Shaman, ClassSpec.Elemental, new[] { 60188, 343190 }, new[] { 27, 52 }, 0, 135830, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.HasteRanged) });
        public Spell FireElemental = new Spell("Fire Elemental", ClassType.Shaman, ClassSpec.Elemental, new[] { 198067 }, new[] { 34 }, 0, 135790, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell FireElementalTotem = new Spell("Fire Elemental Totem", ClassType.Shaman, ClassSpec.Elemental, new[] { 343226 }, new[] { 58 }, 0, 135790, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell FulminationController = new Spell("Fulmination Controller", ClassType.Shaman, ClassSpec.Elemental, new[] { 190488 }, new[] { 10 }, 0, 236299, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcOnPowerAmount), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcOnPowerAmount2) });
        public Spell Icefury = new Spell("Icefury", ClassType.Shaman, ClassSpec.Elemental, new[] { 210714 }, new[] { 1 }, 18, 135855, new double[] { 0 }, new double[] { 15 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell LavaBurst = new Spell("Lava Burst", ClassType.Shaman, ClassSpec.Elemental, new[] { 51505, 231721 }, new[] { 11, 20 }, 0, 237582, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerMissile, EffectAuraType.None) });
        public Spell LavaSurge = new Spell("Lava Surge", ClassType.Shaman, ClassSpec.Elemental, new[] { 77756 }, new[] { 29 }, 0, 451169, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell LiquidMagmaTotem = new Spell("Liquid Magma Totem", ClassType.Shaman, ClassSpec.Elemental, new[] { 192222 }, new[] { 1 }, 12, 971079, new double[] { 0 }, new double[] { 15 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None) });
        public Spell Maelstrom = new Spell("Maelstrom", ClassType.Shaman, ClassSpec.Elemental, new[] { 187828, 343725 }, new[] { 10 }, 0, 462324, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAttackerSpellCritChance), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModManaRegenFromStat) });
        public Spell MasterOfTheElements = new Spell("Master of the Elements", ClassType.Shaman, ClassSpec.Elemental, new[] { 16166 }, new[] { 1 }, 10, 136027, new double[] { }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell MasteryElementalOverload = new Spell("Mastery: Elemental Overload", ClassType.Shaman, ClassSpec.Elemental, new[] { 168534 }, new[] { 10 }, 0, 136050, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SpiritWolf = new Spell("Spirit Wolf", ClassType.Shaman, ClassSpec.Elemental, new[] { 260878 }, new[] { 1 }, 7, 1033494, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SpiritwalkersGrace = new Spell("Spiritwalker's Grace", ClassType.Shaman, ClassSpec.Elemental, new[] { 79206 }, new[] { 44 }, 0, 451170, new double[] { 0 }, new double[] { 15 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.CastWhileWalking), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.HealAbsorbTest), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModSpeedAlways) });
        public Spell StaticCharge = new Spell("Static Charge", ClassType.Shaman, ClassSpec.Elemental, new[] { 265046 }, new[] { 1 }, 9, 136013, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell StaticDischarge = new Spell("Static Discharge", ClassType.Shaman, ClassSpec.Elemental, new[] { 342243 }, new[] { 1 }, 3, 135990, new double[] { 0 }, new double[] { 3 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicTriggerSpell) });
        public Spell StormElemental = new Spell("Storm Elemental", ClassType.Shaman, ClassSpec.Elemental, new[] { 192249 }, new[] { 1 }, 11, 2065626, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Stormkeeper = new Spell("Stormkeeper", ClassType.Shaman, ClassSpec.Elemental, new[] { 191634 }, new[] { 0 }, 20, 839977, new double[] { 0 }, new double[] { 15 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell Thunderstorm = new Spell("Thunderstorm", ClassType.Shaman, ClassSpec.Elemental, new[] { 51490 }, new[] { 49 }, 0, 237589, new double[] { 45 }, new double[] { 5 }, false, 0, new[] { "Thunderstorm" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDecreaseSpeed), new SpellEffectData(SpellEffectName.KnockBack, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell UnlimitedPower = new Spell("Unlimited Power", ClassType.Shaman, ClassSpec.Elemental, new[] { 260895 }, new[] { 1 }, 19, 643246, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
    }
}