namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Feral : Druid
    {
        public Spell Berserk = new Spell("Berserk", ClassType.Druid, ClassSpec.Feral, new[] { 106951, 343223 }, new[] { 34, 58 }, 0, 236149, new double[] { 180 }, new double[] { 20 }, false, 0, new[] { "Berserk" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Bloodtalons = new Spell("Bloodtalons", ClassType.Druid, ClassSpec.Feral, new[] { 319439 }, new[] { 0 }, 20, 1033474, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell BrutalSlash = new Spell("Brutal Slash", ClassType.Druid, ClassSpec.Feral, new[] { 202028 }, new[] { 1 }, 17, 132141, new double[] { 0 }, new double[] { }, false, 8, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell FelineAdept = new Spell("Feline Adept", ClassType.Druid, ClassSpec.Feral, new[] { 300349 }, new[] { 19 }, 0, 611425, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell FelineSwiftness = new Spell("Feline Swiftness", ClassType.Druid, ClassSpec.Feral, new[] { 131768 }, new[] { 27 }, 0, 538517, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModSpeedAlways) });
        public Spell FeralFrenzy = new Spell("Feral Frenzy", ClassType.Druid, ClassSpec.Feral, new[] { 274837 }, new[] { 0 }, 21, 132140, new double[] { 0 }, new double[] { 1 }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell FeralInstinct = new Spell("Feral Instinct", ClassType.Druid, ClassSpec.Feral, new[] { 16949 }, new[] { 16 }, 0, 132089, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModStealthLevel) });
        public Spell FeralOverridesPassive = new Spell("Feral Overrides Passive", ClassType.Druid, ClassSpec.Feral, new[] { 197692 }, new[] { 1 }, 0, 135724, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell GuardianAffinity = new Spell("Guardian Affinity", ClassType.Druid, ClassSpec.Feral, new[] { 217615 }, new[] { 1 }, 8, 611424, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.OverrideActionbarSpells) });
        public Spell IncarnationKingOfTheJungle = new Spell("Incarnation: King of the Jungle", ClassType.Druid, ClassSpec.Feral, new[] { 102543 }, new[] { 1 }, 15, 571586, new double[] { 180 }, new double[] { 30 }, false, 0, new[] { "Incarnation" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell InfectedWounds = new Spell("Infected Wounds", ClassType.Druid, ClassSpec.Feral, new[] { 48484 }, new[] { 37 }, 0, 236158, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell LeatherSpecialization = new Spell("Leather Specialization", ClassType.Druid, ClassSpec.Feral, new[] { 86097 }, new[] { 27 }, 0, 132721, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModTotalStatPercentage) });
        public Spell Maim = new Spell("Maim", ClassType.Druid, ClassSpec.Feral, new[] { 22570 }, new[] { 28 }, 0, 132134, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell MasteryRazorClaws = new Spell("Mastery: Razor Claws", ClassType.Druid, ClassSpec.Feral, new[] { 77493 }, new[] { 10 }, 0, 237389, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MomentOfClarity = new Spell("Moment of Clarity", ClassType.Druid, ClassSpec.Feral, new[] { 236068 }, new[] { 0 }, 19, 1033483, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModIncreaseEnergy) });
        public Spell OmenOfClarity = new Spell("Omen of Clarity", ClassType.Druid, ClassSpec.Feral, new[] { 16864 }, new[] { 33 }, 0, 136017, new double[] { }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Predator = new Spell("Predator", ClassType.Druid, ClassSpec.Feral, new[] { 202021 }, new[] { 0 }, 1, 132167, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell PredatorySwiftness = new Spell("Predatory Swiftness", ClassType.Druid, ClassSpec.Feral, new[] { 16974 }, new[] { 49 }, 0, 132185, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell PrimalFury = new Spell("Primal Fury", ClassType.Druid, ClassSpec.Feral, new[] { 159286 }, new[] { 31 }, 0, 132278, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell PrimalWrath = new Spell("Primal Wrath", ClassType.Druid, ClassSpec.Feral, new[] { 285381 }, new[] { 0 }, 18, 1392547, new double[] { 0 }, new double[] { }, false, 8, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Rake = new Spell("Rake", ClassType.Druid, ClassSpec.Feral, new[] { 1822, 231052 }, new[] { 10, 39 }, 0, 132122, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell RemoveCorruption = new Spell("Remove Corruption", ClassType.Druid, ClassSpec.Feral, new[] { 2782 }, new[] { 19 }, 0, 135952, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dispel, EffectAuraType.None) });
        public Spell Rip = new Spell("Rip", ClassType.Druid, ClassSpec.Feral, new[] { 1079 }, new[] { 21 }, 0, 132152, new double[] { 0 }, new double[] { 4 }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Sabertooth = new Spell("Sabertooth", ClassType.Druid, ClassSpec.Feral, new[] { 202031 }, new[] { 0 }, 2, 134298, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ScentOfBlood = new Spell("Scent of Blood", ClassType.Druid, ClassSpec.Feral, new[] { 285564 }, new[] { 0 }, 16, 451161, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ShapeshiftForm = new Spell("Shapeshift Form", ClassType.Druid, ClassSpec.Feral, new[] { 228545 }, new[] { 1 }, 0, 132115, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Shred = new Spell("Shred", ClassType.Druid, ClassSpec.Feral, new[] { 231057, 231063, 343232 }, new[] { 36, 42, 54 }, 0, 136231, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SkullBash = new Spell("Skull Bash", ClassType.Druid, ClassSpec.Feral, new[] { 106839 }, new[] { 26 }, 0, 236946, new double[] { 15 }, new double[] { }, false, 13, new[] { "Skull Bash" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell SoulOfTheForest = new Spell("Soul of the Forest", ClassType.Druid, ClassSpec.Feral, new[] { 158476 }, new[] { 0 }, 13, 236160, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SurvivalInstincts = new Spell("Survival Instincts", ClassType.Druid, ClassSpec.Feral, new[] { 61336 }, new[] { 32 }, 0, 236169, new double[] { 0 }, new double[] { 6 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Swipe = new Spell("Swipe", ClassType.Druid, ClassSpec.Feral, new[] { 213764, 231283 }, new[] { 23, 42 }, 0, 134296, new double[] { 0 }, new double[] { }, false, 8, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Thrash = new Spell("Thrash", ClassType.Druid, ClassSpec.Feral, new[] { 106832 }, new[] { 11 }, 0, 451161, new double[] { }, new double[] { }, false, 5, new string[] { }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell TigersFury = new Spell("Tiger's Fury", ClassType.Druid, ClassSpec.Feral, new[] { 5217, 231055 }, new[] { 12, 47 }, 0, 132242, new double[] { 0 }, new double[] { 10 }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAutoattackDamage), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None) });

        // Todo: Missing -- put the spell description on the summary?
        public Spell SavageRoar = new Spell("Savage Roar", ClassType.Druid, ClassSpec.Feral, 52610, 0);
    }
}