namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class FrostMage : Mage
    {
        public Spell AlterTime = new Spell("Alter Time", ClassType.Mage, ClassSpec.FrostMage, new[] { 108978 }, new[] { 58 }, 0, 609811, new double[] { 1 }, new double[] { 20 }, false, 0, new[] { "Alter Time" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell Blizzard = new Spell("Blizzard", ClassType.Mage, ClassSpec.FrostMage, new[] { 190356, 236662, 321696 }, new[] { 14, 47, 52 }, 0, 135857, new double[] { 0 }, new double[] { 8 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.CreateAreaTrigger, EffectAuraType.None), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell BoneChilling = new Spell("Bone Chilling", ClassType.Mage, ClassSpec.FrostMage, new[] { 205027 }, new[] { 1 }, 1, 236208, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell BrainFreeze = new Spell("Brain Freeze", ClassType.Mage, ClassSpec.FrostMage, new[] { 190447, 231584 }, new[] { 32, 37 }, 0, 236206, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ChainReaction = new Spell("Chain Reaction", ClassType.Mage, ClassSpec.FrostMage, new[] { 278309 }, new[] { 0 }, 11, 135844, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ColdSnap = new Spell("Cold Snap", ClassType.Mage, ClassSpec.FrostMage, new[] { 235219, 321699 }, new[] { 42, 54 }, 0, 135865, new double[] { 0 }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ScriptEffect, EffectAuraType.None) });
        public Spell CometStorm = new Spell("Comet Storm", ClassType.Mage, ClassSpec.FrostMage, new[] { 153595 }, new[] { 0 }, 18, 2126034, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell ConeOfCold = new Spell("Cone of Cold", ClassType.Mage, ClassSpec.FrostMage, new[] { 120, 343180 }, new[] { 18, 43 }, 0, 135852, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModManaRegenFromStat), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Ebonbolt = new Spell("Ebonbolt", ClassType.Mage, ClassSpec.FrostMage, new[] { 257537 }, new[] { 0 }, 12, 1392551, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell FingersOfFrost = new Spell("Fingers of Frost", ClassType.Mage, ClassSpec.FrostMage, new[] { 112965 }, new[] { 13 }, 0, 236227, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Flurry = new Spell("Flurry", ClassType.Mage, ClassSpec.FrostMage, new[] { 44614 }, new[] { 19 }, 0, 1506795, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerMissile, EffectAuraType.None) });
        public Spell Freeze = new Spell("Freeze", ClassType.Mage, ClassSpec.FrostMage, new[] { 231596 }, new[] { 23 }, 0, 1698698, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell FreezingRain = new Spell("Freezing Rain", ClassType.Mage, ClassSpec.FrostMage, new[] { 270233 }, new[] { 0 }, 16, 629077, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell FrigidWinds = new Spell("Frigid Winds", ClassType.Mage, ClassSpec.FrostMage, new[] { 235224 }, new[] { 1 }, 13, 236214, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell FrostNova = new Spell("Frost Nova", ClassType.Mage, ClassSpec.FrostMage, new[] { 343183 }, new[] { 46 }, 0, 135848, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell Frostbolt = new Spell("Frostbolt", ClassType.Mage, ClassSpec.FrostMage, new[] { 343177 }, new[] { 41 }, 0, 135846, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell FrozenOrb = new Spell("Frozen Orb", ClassType.Mage, ClassSpec.FrostMage, new[] { 84714 }, new[] { 38 }, 0, 629077, new double[] { 60 }, new double[] { 15 }, false, 40, new[] { "Flame Orb" }, new[] { new SpellEffectData(SpellEffectName.CreateAreaTrigger, EffectAuraType.None) });
        public Spell FrozenTouch = new Spell("Frozen Touch", ClassType.Mage, ClassSpec.FrostMage, new[] { 205030 }, new[] { 1 }, 10, 1387352, new double[] { 0 }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell GlacialInsulation = new Spell("Glacial Insulation", ClassType.Mage, ClassSpec.FrostMage, new[] { 235297 }, new[] { 1 }, 4, 236209, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell GlacialSpike = new Spell("Glacial Spike", ClassType.Mage, ClassSpec.FrostMage, new[] { 199786 }, new[] { 0 }, 21, 1698699, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell IceBarrier = new Spell("Ice Barrier", ClassType.Mage, ClassSpec.FrostMage, new[] { 11426 }, new[] { 11 }, 0, 135988, new double[] { 25 }, new double[] { 60 }, false, 0, new[] { "Ice Barrier" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModBaseResistancePct), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.SchoolAbsorb) });
        public Spell IceFloes = new Spell("Ice Floes", ClassType.Mage, ClassSpec.FrostMage, new[] { 108839 }, new[] { 1 }, 6, 610877, new double[] { }, new double[] { 15 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.CastWhileWalking), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.HealAbsorbTest), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell IceLance = new Spell("Ice Lance", ClassType.Mage, ClassSpec.FrostMage, new[] { 30455, 343175 }, new[] { 10, 33 }, 0, 135844, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ScriptEffect, EffectAuraType.None) });
        public Spell IceNova = new Spell("Ice Nova", ClassType.Mage, ClassSpec.FrostMage, new[] { 157997 }, new[] { 1 }, 3, 1033909, new double[] { 0 }, new double[] { 2 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModRoot2), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell IcyVeins = new Spell("Icy Veins", ClassType.Mage, ClassSpec.FrostMage, new[] { 12472, 321702 }, new[] { 29, 56 }, 0, 135838, new double[] { 0 }, new double[] { 20 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.MeleeSlow) });
        public Spell LonelyWinter = new Spell("Lonely Winter", ClassType.Mage, ClassSpec.FrostMage, new[] { 205024 }, new[] { 1 }, 2, 342402, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell MasteryIcicles = new Spell("Mastery: Icicles", ClassType.Mage, ClassSpec.FrostMage, new[] { 76613, 321684 }, new[] { 10, 48 }, 0, 135855, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell RayOfFrost = new Spell("Ray of Frost", ClassType.Mage, ClassSpec.FrostMage, new[] { 205021 }, new[] { 1 }, 20, 1698700, new double[] { 0 }, new double[] { 5 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDecreaseSpeed), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Shatter = new Spell("Shatter", ClassType.Mage, ClassSpec.FrostMage, new[] { 12982, 231582 }, new[] { 17, 27 }, 0, 135849, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.OverrideClassScripts) });
        public Spell SplittingIce = new Spell("Splitting Ice", ClassType.Mage, ClassSpec.FrostMage, new[] { 56377 }, new[] { 0 }, 17, 429385, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell SummonWaterElemental = new Spell("Summon Water Elemental", ClassType.Mage, ClassSpec.FrostMage, new[] { 31687 }, new[] { 12 }, 0, 135862, new double[] { 0 }, new double[] { -0.001 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.SummonPet, EffectAuraType.None) });
        public Spell ThermalVoid = new Spell("Thermal Void", ClassType.Mage, ClassSpec.FrostMage, new[] { 155149 }, new[] { 0 }, 19, 1036179, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
    }
}