namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Frost : DeathKnight
    {
        public Spell Asphyxiate = new Spell("Asphyxiate", ClassType.DeathKnight, ClassSpec.Frost, new[] { 108194 }, new[] { 0 }, 8, 538558, new double[] { 0 }, new double[] { 4 }, false, 20, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Strangulate) });
        public Spell Avalanche = new Spell("Avalanche", ClassType.DeathKnight, ClassSpec.Frost, new[] { 207142 }, new[] { 1 }, 10, 135857, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell BlindingSleet = new Spell("Blinding Sleet", ClassType.DeathKnight, ClassSpec.Frost, new[] { 207167 }, new[] { 1 }, 9, 135836, new double[] { 0 }, new double[] { 5 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModConfuse), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDecreaseSpeed) });
        public Spell BreathOfSindragosa = new Spell("Breath of Sindragosa", ClassType.DeathKnight, ClassSpec.Frost, new[] { 152279 }, new[] { 0 }, 21, 1029007, new double[] { 0 }, new double[] { -0.001 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicTriggerSpell), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell ColdHeart = new Spell("Cold Heart", ClassType.DeathKnight, ClassSpec.Frost, new[] { 281208 }, new[] { 0 }, 3, 135851, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicTriggerSpell) });
        public Spell DarkSuccor = new Spell("Dark Succor", ClassType.DeathKnight, ClassSpec.Frost, new[] { 178819 }, new[] { 18 }, 0, 878217, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell DeathStrike = new Spell("Death Strike", ClassType.DeathKnight, ClassSpec.Frost, new[] { 278223 }, new[] { 28 }, 0, 237517, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell DeathsReach = new Spell("Death's Reach", ClassType.DeathKnight, ClassSpec.Frost, new[] { 276079 }, new[] { 0 }, 7, 237532, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell EmpowerRuneWeapon = new Spell("Empower Rune Weapon", ClassType.DeathKnight, ClassSpec.Frost, new[] { 47568, 317230 }, new[] { 48, 56 }, 0, 135372, new double[] { }, new double[] { 20 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ChargeRecoveryMod), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.MeleeSlow), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicEnergize) });
        public Spell FrostStrike = new Spell("Frost Strike", ClassType.DeathKnight, ClassSpec.Frost, new[] { 49143, 316803 }, new[] { 11, 43 }, 0, 237520, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell Frostscythe = new Spell("Frostscythe", ClassType.DeathKnight, ClassSpec.Frost, new[] { 207230 }, new[] { 1 }, 12, 1060569, new double[] { 0 }, new double[] { }, false, 8, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell FrostwyrmsFury = new Spell("Frostwyrm's Fury", ClassType.DeathKnight, ClassSpec.Frost, new[] { 279302 }, new[] { 44 }, 0, 341980, new double[] { 0 }, new double[] { 10 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.CreateAreaTrigger, EffectAuraType.None) });
        public Spell FrozenPulse = new Spell("Frozen Pulse", ClassType.DeathKnight, ClassSpec.Frost, new[] { 194909 }, new[] { 0 }, 11, 1029742, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell GatheringStorm = new Spell("Gathering Storm", ClassType.DeathKnight, ClassSpec.Frost, new[] { 194912 }, new[] { 0 }, 16, 429385, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell HornOfWinter = new Spell("Horn of Winter", ClassType.DeathKnight, ClassSpec.Frost, new[] { 57330 }, new[] { 1 }, 6, 134228, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None) });
        public Spell HowlingBlast = new Spell("Howling Blast", ClassType.DeathKnight, ClassSpec.Frost, new[] { 49184 }, new[] { 10 }, 0, 135833, new double[] { 0 }, new double[] { }, false, 30, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell HypothermicPresence = new Spell("Hypothermic Presence", ClassType.DeathKnight, ClassSpec.Frost, new[] { 321995 }, new[] { 0 }, 17, 236224, new double[] { 0 }, new double[] { 8 }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModPowerCostSchoolPct) });
        public Spell Icecap = new Spell("Icecap", ClassType.DeathKnight, ClassSpec.Frost, new[] { 207126 }, new[] { 1 }, 19, 134212, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell IcyTalons = new Spell("Icy Talons", ClassType.DeathKnight, ClassSpec.Frost, new[] { 194878 }, new[] { 0 }, 2, 252994, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell InexorableAssault = new Spell("Inexorable Assault", ClassType.DeathKnight, ClassSpec.Frost, new[] { 253593 }, new[] { 1 }, 1, 343637, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy) });
        public Spell KillingMachine = new Spell("Killing Machine", ClassType.DeathKnight, ClassSpec.Frost, new[] { 51128, 317214 }, new[] { 23, 58 }, 0, 135305, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell MasteryFrozenHeart = new Spell("Mastery: Frozen Heart", ClassType.DeathKnight, ClassSpec.Frost, new[] { 77514 }, new[] { 10 }, 0, 134131, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell MightOfTheFrozenWastes = new Spell("Might of the Frozen Wastes", ClassType.DeathKnight, ClassSpec.Frost, new[] { 81333, 343252 }, new[] { 10, 24 }, 0, 135303, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MurderousEfficiency = new Spell("Murderous Efficiency", ClassType.DeathKnight, ClassSpec.Frost, new[] { 207061 }, new[] { 1 }, 5, 135842, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Obliterate = new Spell("Obliterate", ClassType.DeathKnight, ClassSpec.Frost, new[] { 49020, 317198 }, new[] { 14, 52 }, 0, 135771, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell Obliteration = new Spell("Obliteration", ClassType.DeathKnight, ClassSpec.Frost, new[] { 281238 }, new[] { 0 }, 20, 326443, new double[] { }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Permafrost = new Spell("Permafrost", ClassType.DeathKnight, ClassSpec.Frost, new[] { 207200 }, new[] { 1 }, 13, 1031536, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell PillarOfFrost = new Spell("Pillar of Frost", ClassType.DeathKnight, ClassSpec.Frost, new[] { 51271, 316849 }, new[] { 29, 49 }, 0, 458718, new double[] { 0 }, new double[] { 12 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentDone), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModTotalStatPercentage) });
        public Spell RemorselessWinter = new Spell("Remorseless Winter", ClassType.DeathKnight, ClassSpec.Frost, new[] { 196770, 316794 }, new[] { 19, 34 }, 0, 538770, new double[] { 0 }, new double[] { 8 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AreaTrigger), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicTriggerSpell), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Rime = new Spell("Rime", ClassType.DeathKnight, ClassSpec.Frost, new[] { 59057, 316838 }, new[] { 32, 41 }, 0, 135840, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell RunicAttenuation = new Spell("Runic Attenuation", ClassType.DeathKnight, ClassSpec.Frost, new[] { 207104 }, new[] { 0 }, 4, 1323035, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell RunicEmpowerment = new Spell("Runic Empowerment", ClassType.DeathKnight, ClassSpec.Frost, new[] { 81229 }, new[] { 21 }, 0, 134423, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell WraithWalk = new Spell("Wraith Walk", ClassType.DeathKnight, ClassSpec.Frost, new[] { 212552 }, new[] { 25 }, 14, 1100041, new double[] { 0 }, new double[] { 4 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData((SpellEffectName)0, EffectAuraType.None), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Hover), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDetectRange), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModIncreaseSpeed), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMinimumSpeed), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
    }
}