namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Fury : Warrior
    {
        public Spell AngerManagement = new Spell("Anger Management", ClassType.Warrior, ClassSpec.Fury, new[] { 152278 }, new[] { 0 }, 19, 971080, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Bladestorm = new Spell("Bladestorm", ClassType.Warrior, ClassSpec.Fury, new[] { 46924 }, new[] { 29 }, 18, 236303, new double[] { 0 }, new double[] { 4 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AllowOnlyAbility), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.MechanicImmunityMask), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicEnergize), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicTriggerSpell) });
        public Spell Bloodthirst = new Spell("Bloodthirst", ClassType.Warrior, ClassSpec.Fury, new[] { 23881, 316537 }, new[] { 10, 48 }, 0, 136012, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Cruelty = new Spell("Cruelty", ClassType.Warrior, ClassSpec.Fury, new[] { 335070 }, new[] { 0 }, 15, 136035, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell DragonRoar = new Spell("Dragon Roar", ClassType.Warrior, ClassSpec.Fury, new[] { 118000 }, new[] { 1 }, 17, 642418, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell DualWield = new Spell("Dual Wield", ClassType.Warrior, ClassSpec.Fury, new[] { 231842 }, new[] { 10 }, 0, 132147, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.DualWield, EffectAuraType.None) });
        public Spell Enrage = new Spell("Enrage", ClassType.Warrior, ClassSpec.Fury, new[] { 184361, 316424, 316425 }, new[] { 10, 20, 49 }, 0, 136224, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell EnragedRegeneration = new Spell("Enraged Regeneration", ClassType.Warrior, ClassSpec.Fury, new[] { 184364, 316474 }, new[] { 23, 32 }, 0, 132345, new double[] { 0 }, new double[] { 8 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken) });
        public Spell Execute = new Spell("Execute", ClassType.Warrior, ClassSpec.Fury, new[] { 5308, 231827, 316402, 316403 }, new[] { 9, 13, 18, 58 }, 0, 135358, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAdditionalPowerCost), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell Frenzy = new Spell("Frenzy", ClassType.Warrior, ClassSpec.Fury, new[] { 335077 }, new[] { 0 }, 8, 132284, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell FreshMeat = new Spell("Fresh Meat", ClassType.Warrior, ClassSpec.Fury, new[] { 215568 }, new[] { 0 }, 3, 538039, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell FrothingBerserker = new Spell("Frothing Berserker", ClassType.Warrior, ClassSpec.Fury, new[] { 215571 }, new[] { 0 }, 14, 458971, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell FuriousCharge = new Spell("Furious Charge", ClassType.Warrior, ClassSpec.Fury, new[] { 202224 }, new[] { 0 }, 10, 1380675, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ImpendingVictory = new Spell("Impending Victory", ClassType.Warrior, ClassSpec.Fury, new[] { 202168 }, new[] { 0 }, 5, 589768, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Massacre = new Spell("Massacre", ClassType.Warrior, ClassSpec.Fury, new[] { 206315 }, new[] { 0 }, 7, 135358, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.OverrideActionbarSpells) });
        public Spell MasteryUnshackledFury = new Spell("Mastery: Unshackled Fury", ClassType.Warrior, ClassSpec.Fury, new[] { 76856 }, new[] { 10 }, 0, 132344, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAutoattackDamage) });
        public Spell MeatCleaver = new Spell("Meat Cleaver", ClassType.Warrior, ClassSpec.Fury, new[] { 280392 }, new[] { 0 }, 16, 132369, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Onslaught = new Spell("Onslaught", ClassType.Warrior, ClassSpec.Fury, new[] { 315720 }, new[] { 0 }, 9, 132364, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell PiercingHowl = new Spell("Piercing Howl", ClassType.Warrior, ClassSpec.Fury, new[] { 12323 }, new[] { 21 }, 0, 136147, new double[] { 0 }, new double[] { 8 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDecreaseSpeed) });
        public Spell RagingBlow = new Spell("Raging Blow", ClassType.Warrior, ClassSpec.Fury, new[] { 85288, 316452, 316453 }, new[] { 12, 27, 42 }, 0, 589119, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxCharges), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell Rampage = new Spell("Rampage", ClassType.Warrior, ClassSpec.Fury, new[] { 184367, 316412, 316519 }, new[] { 19, 28, 44 }, 0, 132352, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell Rampage_ = new Spell("Rampage!", ClassType.Warrior, ClassSpec.Fury, new[] { 209694 }, new[] { 19 }, 0, 132352, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcOnPowerAmount2), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell RecklessAbandon = new Spell("Reckless Abandon", ClassType.Warrior, ClassSpec.Fury, new[] { 202751 }, new[] { 0 }, 20, 132333, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Recklessness = new Spell("Recklessness", ClassType.Warrior, ClassSpec.Fury, new[] { 1719, 316828 }, new[] { 38, 52 }, 0, 458972, new double[] { 0 }, new double[] { 10 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModRageFromDamageDealt), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.ScriptEffect, EffectAuraType.None) });
        public Spell Seethe = new Spell("Seethe", ClassType.Warrior, ClassSpec.Fury, new[] { 335091 }, new[] { 0 }, 13, 236308, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Siegebreaker = new Spell("Siegebreaker", ClassType.Warrior, ClassSpec.Fury, new[] { 280772 }, new[] { 0 }, 21, 294382, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Single_MindedFury = new Spell("Single-Minded Fury", ClassType.Warrior, ClassSpec.Fury, new[] { 81099 }, new[] { 14 }, 0, 458974, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAutoattackDamage), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModSpeedAlways) });
        public Spell StormBolt = new Spell("Storm Bolt", ClassType.Warrior, ClassSpec.Fury, new[] { 107570 }, new[] { 0 }, 6, 613535, new double[] { 0 }, new double[] { }, false, 20, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell SuddenDeath = new Spell("Sudden Death", ClassType.Warrior, ClassSpec.Fury, new[] { 280721 }, new[] { 0 }, 2, 132346, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell TitansGrip = new Spell("Titan's Grip", ClassType.Warrior, ClassSpec.Fury, new[] { 46917 }, new[] { 14 }, 0, 236316, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.TitanGrip, EffectAuraType.None) });
        public Spell WarMachine = new Spell("War Machine", ClassType.Warrior, ClassSpec.Fury, new[] { 346002 }, new[] { 0 }, 1, 132205, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModRageFromDamageDealt), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Warpaint = new Spell("Warpaint", ClassType.Warrior, ClassSpec.Fury, new[] { 208154 }, new[] { 0 }, 12, 460693, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell Whirlwind = new Spell("Whirlwind", ClassType.Warrior, ClassSpec.Fury, new[] { 12950, 190411, 316435 }, new[] { 9, 22, 37 }, 0, 132369, new double[] { 0 }, new double[] { }, false, 0, new[] { "Whirlwind" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
    }
}