namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Guardian : Druid
    {
        public Spell BearForm = new Spell("Bear Form", ClassType.Druid, ClassSpec.Guardian, new[] { 270100 }, new[] { 12 }, 0, 132276, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell Berserk = new Spell("Berserk", ClassType.Druid, ClassSpec.Guardian, new[] { 50334, 343240 }, new[] { 34, 58 }, 0, 236149, new double[] { 180 }, new double[] { 15 }, false, 0, new[] { "Berserk" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ChargeRecoveryMultiplier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.MechanicImmunityMask), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.MeleeSlow), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAutoattackDamage), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModLeech) });
        public Spell BloodFrenzy = new Spell("Blood Frenzy", ClassType.Druid, ClassSpec.Guardian, new[] { 203962 }, new[] { 0 }, 2, 132139, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Brambles = new Spell("Brambles", ClassType.Druid, ClassSpec.Guardian, new[] { 203953 }, new[] { 0 }, 1, 415052, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.SchoolAbsorb) });
        public Spell Earthwarden = new Spell("Earthwarden", ClassType.Druid, ClassSpec.Guardian, new[] { 203974 }, new[] { 0 }, 16, 237573, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell FeralAffinity = new Spell("Feral Affinity", ClassType.Druid, ClassSpec.Guardian, new[] { 202155 }, new[] { 1 }, 8, 611425, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModPowerRegenPercent), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.OverrideActionbarSpells) });
        public Spell FrenziedRegeneration = new Spell("Frenzied Regeneration", ClassType.Druid, ClassSpec.Guardian, new[] { 22842, 273048, 301768 }, new[] { 21, 39, 54 }, 0, 132091, new double[] { 0 }, new double[] { 3 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModHealingPct), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxCharges), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ObsModHealth) });
        public Spell GalacticGuardian = new Spell("Galactic Guardian", ClassType.Druid, ClassSpec.Guardian, new[] { 203964 }, new[] { 0 }, 14, 135853, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Gore = new Spell("Gore", ClassType.Druid, ClassSpec.Guardian, new[] { 210706 }, new[] { 37 }, 0, 571585, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell GuardianOfElune = new Spell("Guardian of Elune", ClassType.Druid, ClassSpec.Guardian, new[] { 155578 }, new[] { 0 }, 18, 1033479, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell IncapacitatingRoar = new Spell("Incapacitating Roar", ClassType.Druid, ClassSpec.Guardian, new[] { 99 }, new[] { 28 }, 0, 132121, new double[] { 0 }, new double[] { 3 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModConfuse), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDecreaseSpeed) });
        public Spell IncarnationGuardianOfUrsoc = new Spell("Incarnation: Guardian of Ursoc", ClassType.Druid, ClassSpec.Guardian, new[] { 102558 }, new[] { 1 }, 15, 571586, new double[] { 180 }, new double[] { 30 }, false, 0, new[] { "Incarnation" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ChargeRecoveryMultiplier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.MechanicImmunityMask), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.MeleeSlow), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAutoattackDamage), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModIncreaseHealthPercent), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModLeech) });
        public Spell InfectedWounds = new Spell("Infected Wounds", ClassType.Druid, ClassSpec.Guardian, new[] { 345208 }, new[] { 37 }, 0, 236158, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Ironfur = new Spell("Ironfur", ClassType.Druid, ClassSpec.Guardian, new[] { 231070 }, new[] { 33 }, 0, 1378702, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell LeatherSpecialization = new Spell("Leather Specialization", ClassType.Druid, ClassSpec.Guardian, new[] { 86096 }, new[] { 27 }, 0, 132721, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModTotalStatPercentage) });
        public Spell LightningReflexes = new Spell("Lightning Reflexes", ClassType.Druid, ClassSpec.Guardian, new[] { 231065 }, new[] { 47 }, 0, 1509620, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, (EffectAuraType)198) });
        public Spell Mangle = new Spell("Mangle", ClassType.Druid, ClassSpec.Guardian, new[] { 231064 }, new[] { 42 }, 0, 132135, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MasteryNaturesGuardian = new Spell("Mastery: Nature's Guardian", ClassType.Druid, ClassSpec.Guardian, new[] { 155783 }, new[] { 10 }, 0, 1033485, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, (EffectAuraType)422), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModIncreaseHealthPercent) });
        public Spell Maul = new Spell("Maul", ClassType.Druid, ClassSpec.Guardian, new[] { 6807 }, new[] { 10 }, 0, 132136, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Pulverize = new Spell("Pulverize", ClassType.Druid, ClassSpec.Guardian, new[] { 80313 }, new[] { 1 }, 21, 1033490, new double[] { 0 }, new double[] { 10 }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModIgnoreTargetResist), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell RemoveCorruption = new Spell("Remove Corruption", ClassType.Druid, ClassSpec.Guardian, new[] { 2782 }, new[] { 19 }, 0, 135952, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dispel, EffectAuraType.None) });
        public Spell RendAndTear = new Spell("Rend and Tear", ClassType.Druid, ClassSpec.Guardian, new[] { 204053 }, new[] { 0 }, 19, 132143, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell ShapeshiftForm = new Spell("Shapeshift Form", ClassType.Druid, ClassSpec.Guardian, new[] { 228545 }, new[] { 1 }, 0, 132115, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell SkullBash = new Spell("Skull Bash", ClassType.Druid, ClassSpec.Guardian, new[] { 106839 }, new[] { 26 }, 0, 236946, new double[] { 15 }, new double[] { }, false, 13, new[] { "Skull Bash" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell SoulOfTheForest = new Spell("Soul of the Forest", ClassType.Druid, ClassSpec.Guardian, new[] { 158477 }, new[] { 0 }, 13, 236160, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell StampedingRoar = new Spell("Stampeding Roar", ClassType.Druid, ClassSpec.Guardian, new[] { 288826 }, new[] { 49 }, 0, 463283, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell SurvivalInstincts = new Spell("Survival Instincts", ClassType.Druid, ClassSpec.Guardian, new[] { 61336, 328767 }, new[] { 32, 47 }, 0, 236169, new double[] { 0 }, new double[] { 6 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxCharges) });
        public Spell Swipe = new Spell("Swipe", ClassType.Druid, ClassSpec.Guardian, new[] { 213764 }, new[] { 23 }, 0, 134296, new double[] { 0 }, new double[] { }, false, 8, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell ThickHide = new Spell("Thick Hide", ClassType.Druid, ClassSpec.Guardian, new[] { 16931 }, new[] { 27 }, 0, 134355, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken) });
        public Spell Thrash = new Spell("Thrash", ClassType.Druid, ClassSpec.Guardian, new[] { 106832 }, new[] { 11 }, 0, 451161, new double[] { }, new double[] { }, false, 5, new string[] { }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell ToothAndClaw = new Spell("Tooth and Claw", ClassType.Druid, ClassSpec.Guardian, new[] { 135288 }, new[] { 0 }, 20, 134298, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell UrsineAdept = new Spell("Ursine Adept", ClassType.Druid, ClassSpec.Guardian, new[] { 300346 }, new[] { 10 }, 0, 611424, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });

        // Todo: Bristling Fur missing
        public Spell BristlingFur = new Spell("Bristling Fur", ClassType.Druid, ClassSpec.Guardian, 155835, 3);
    }
}