namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class HolyPaladin : Paladin
    {
        public Spell AuraMastery = new Spell("Aura Mastery", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 31821 }, new[] { 39 }, 0, 135872, new double[] { 0 }, new double[] { 8 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell AvengingCrusader = new Spell("Avenging Crusader", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 216331 }, new[] { 28 }, 17, 589117, new double[] { 0 }, new double[] { 20 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, (EffectAuraType)173), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AbilityIgnoreAuraState), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAutoattackDamage), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModResistanceExclusive) });
        public Spell AvengingWrath = new Spell("Avenging Wrath", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 327979 }, new[] { 48 }, 0, 135875, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell Awakening = new Spell("Awakening", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 248033 }, new[] { 0 }, 18, 898454, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell BeaconOfFaith = new Spell("Beacon of Faith", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 156910 }, new[] { 1 }, 20, 1030095, new double[] { 0 }, new double[] { -0.001 }, false, 60, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModHealingReceived), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell BeaconOfLight = new Spell("Beacon of Light", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 53563, 231642 }, new[] { 19, 42 }, 0, 236247, new double[] { 0 }, new double[] { -0.001 }, false, 60, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModHealingReceived), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell BeaconOfVirtue = new Spell("Beacon of Virtue", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 200025 }, new[] { 1 }, 21, 1030094, new double[] { 0 }, new double[] { 8 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell BestowFaith = new Spell("Bestow Faith", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 223306 }, new[] { 1 }, 2, 236249, new double[] { 0 }, new double[] { 5 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicHeal) });
        public Spell Cleanse = new Spell("Cleanse", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 4987 }, new[] { 12 }, 0, 135949, new double[] { 8 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dispel, EffectAuraType.None) });
        public Spell CrusaderStrike = new Spell("Crusader Strike", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 231667 }, new[] { 33 }, 0, 135891, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxCharges) });
        public Spell CrusadersMight = new Spell("Crusader's Might", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 196926 }, new[] { 0 }, 1, 236266, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell DivineProtection = new Spell("Divine Protection", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 498 }, new[] { 26 }, 0, 524353, new double[] { 0 }, new double[] { 8 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken) });
        public Spell GlimmerOfLight = new Spell("Glimmer of Light", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 325966 }, new[] { 0 }, 19, 1360764, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAttackPowerOfArmor) });
        public Spell HolyLight = new Spell("Holy Light", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 82326 }, new[] { 11 }, 0, 135981, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None) });
        public Spell HolyShock = new Spell("Holy Shock", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 20473, 272906, 289941 }, new[] { 10, 18 }, 0, 135972, new double[] { 7.5 }, new double[] { }, false, 40, new[] { "Holy Shock" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None) });
        public Spell InfusionOfLight = new Spell("Infusion of Light", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 53576 }, new[] { 23 }, 0, 236254, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Judgment = new Spell("Judgment", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 231644 }, new[] { 29 }, 0, 135959, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell JudgmentOfLight = new Spell("Judgment of Light", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 183778 }, new[] { 1 }, 5, 237541, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell LightOfDawn = new Spell("Light of Dawn", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 85222 }, new[] { 34 }, 0, 461859, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell LightOfTheMartyr = new Spell("Light of the Martyr", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 183998, 219562 }, new[] { 1, 27 }, 0, 1360762, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None) });
        public Spell LightsBeacon = new Spell("Light's Beacon", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 53651 }, new[] { 19 }, 0, 236247, new double[] { }, new double[] { }, false, 60, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MasteryLightbringer = new Spell("Mastery: Lightbringer", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 183997 }, new[] { 10 }, 0, 133041, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell RuleOfLaw = new Spell("Rule of Law", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 214202 }, new[] { 1 }, 12, 571556, new double[] { 0 }, new double[] { 10 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAttackerRangedCritChance) });
        public Spell SanctifiedWrath = new Spell("Sanctified Wrath", ClassType.Paladin, ClassSpec.HolyPaladin, new[] { 53376 }, new[] { 0 }, 16, 236259, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
    }
}