namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class HolyPriest : Priest
    {
        public Spell Afterlife = new Spell("Afterlife", ClassType.Priest, ClassSpec.HolyPriest, new[] { 196707 }, new[] { 0 }, 9, 132866, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell AngelsMercy = new Spell("Angel's Mercy", ClassType.Priest, ClassSpec.HolyPriest, new[] { 238100 }, new[] { 0 }, 4, 237550, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Apotheosis = new Spell("Apotheosis", ClassType.Priest, ClassSpec.HolyPriest, new[] { 200183 }, new[] { 1 }, 20, 1060983, new double[] { 0 }, new double[] { 20 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDispelResist), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.WaterWalk) });
        public Spell BindingHeal = new Spell("Binding Heal", ClassType.Priest, ClassSpec.HolyPriest, new[] { 32546 }, new[] { 1 }, 14, 135883, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None) });
        public Spell BodyAndSoul = new Spell("Body and Soul", ClassType.Priest, ClassSpec.HolyPriest, new[] { 64129 }, new[] { 0 }, 5, 135982, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Censure = new Spell("Censure", ClassType.Priest, ClassSpec.HolyPriest, new[] { 200199 }, new[] { 1 }, 11, 135904, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell CircleOfHealing = new Spell("Circle of Healing", ClassType.Priest, ClassSpec.HolyPriest, new[] { 204883 }, new[] { 39 }, 0, 135887, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None) });
        public Spell CosmicRipple = new Spell("Cosmic Ripple", ClassType.Priest, ClassSpec.HolyPriest, new[] { 238136 }, new[] { 0 }, 7, 135980, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell DivineHymn = new Spell("Divine Hymn", ClassType.Priest, ClassSpec.HolyPriest, new[] { 64843 }, new[] { 44 }, 0, 237540, new double[] { 0 }, new double[] { 8 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicTriggerSpell), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Enlightenment = new Spell("Enlightenment", ClassType.Priest, ClassSpec.HolyPriest, new[] { 193155 }, new[] { 0 }, 1, 135740, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModPowerRegenPercent) });
        public Spell FocusedWill = new Spell("Focused Will", ClassType.Priest, ClassSpec.HolyPriest, new[] { 285485 }, new[] { 43 }, 0, 458227, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell GuardianAngel = new Spell("Guardian Angel", ClassType.Priest, ClassSpec.HolyPriest, new[] { 200209 }, new[] { 0 }, 8, 612969, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell GuardianSpirit = new Spell("Guardian Spirit", ClassType.Priest, ClassSpec.HolyPriest, new[] { 47788 }, new[] { 30 }, 0, 237542, new double[] { 0 }, new double[] { 10 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModHealingPct), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicHaste), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Heal = new Spell("Heal", ClassType.Priest, ClassSpec.HolyPriest, new[] { 2060 }, new[] { 15 }, 0, 135913, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None) });
        public Spell HolyFire = new Spell("Holy Fire", ClassType.Priest, ClassSpec.HolyPriest, new[] { 14914 }, new[] { 19 }, 0, 135972, new double[] { 0 }, new double[] { 7 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AreaTrigger), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell HolyNova = new Spell("Holy Nova", ClassType.Priest, ClassSpec.HolyPriest, new[] { 132157, 322112 }, new[] { 31, 56 }, 0, 135922, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData((SpellEffectName)0, EffectAuraType.None), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell HolyWordChastise = new Spell("Holy Word: Chastise", ClassType.Priest, ClassSpec.HolyPriest, new[] { 88625 }, new[] { 23 }, 0, 135886, new double[] { 0 }, new double[] { }, false, 30, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell HolyWordSalvation = new Spell("Holy Word: Salvation", ClassType.Priest, ClassSpec.HolyPriest, new[] { 265202 }, new[] { 27 }, 21, 458225, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None) });
        public Spell HolyWordSanctify = new Spell("Holy Word: Sanctify", ClassType.Priest, ClassSpec.HolyPriest, new[] { 34861 }, new[] { 41 }, 0, 237541, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None) });
        public Spell HolyWordSerenity = new Spell("Holy Word: Serenity", ClassType.Priest, ClassSpec.HolyPriest, new[] { 2050 }, new[] { 11 }, 0, 135937, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None) });
        public Spell HolyWords = new Spell("Holy Words", ClassType.Priest, ClassSpec.HolyPriest, new[] { 63733 }, new[] { 26 }, 0, 237549, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell LightOfTheNaaru = new Spell("Light of the Naaru", ClassType.Priest, ClassSpec.HolyPriest, new[] { 196985 }, new[] { 0 }, 19, 1100172, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MasteryEchoOfLight = new Spell("Mastery: Echo of Light", ClassType.Priest, ClassSpec.HolyPriest, new[] { 77485 }, new[] { 10 }, 0, 237537, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell PrayerCircle = new Spell("Prayer Circle", ClassType.Priest, ClassSpec.HolyPriest, new[] { 321377 }, new[] { 0 }, 15, 457654, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell PrayerOfHealing = new Spell("Prayer of Healing", ClassType.Priest, ClassSpec.HolyPriest, new[] { 596 }, new[] { 32 }, 0, 135943, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell PrayerOfMending = new Spell("Prayer of Mending", ClassType.Priest, ClassSpec.HolyPriest, new[] { 33076, 319912 }, new[] { 43, 48 }, 0, 135944, new double[] { 12 }, new double[] { }, false, 40, new[] { "Prayer of Mending" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell PsychicVoice = new Spell("Psychic Voice", ClassType.Priest, ClassSpec.HolyPriest, new[] { 196704 }, new[] { 0 }, 10, 132339, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell Purify = new Spell("Purify", ClassType.Priest, ClassSpec.HolyPriest, new[] { 527 }, new[] { 18 }, 0, 135894, new double[] { 8 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dispel, EffectAuraType.None) });
        public Spell Renew = new Spell("Renew", ClassType.Priest, ClassSpec.HolyPriest, new[] { 139 }, new[] { 12 }, 0, 135953, new double[] { 0 }, new double[] { 15 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModHealingReceived), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicHeal) });
        public Spell RenewedFaith = new Spell("Renewed Faith", ClassType.Priest, ClassSpec.HolyPriest, new[] { 341997 }, new[] { 1 }, 3, 1322723, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell Smite = new Spell("Smite", ClassType.Priest, ClassSpec.HolyPriest, new[] { 262861 }, new[] { 13 }, 0, 135924, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell SpiritOfRedemption = new Spell("Spirit of Redemption", ClassType.Priest, ClassSpec.HolyPriest, new[] { 20711 }, new[] { 29 }, 0, 132864, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicHaste) });
        public Spell SurgeOfLight = new Spell("Surge of Light", ClassType.Priest, ClassSpec.HolyPriest, new[] { 109186 }, new[] { 0 }, 13, 135981, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SymbolOfHope = new Spell("Symbol of Hope", ClassType.Priest, ClassSpec.HolyPriest, new[] { 64901 }, new[] { 47 }, 0, 135982, new double[] { 0 }, new double[] { 5 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicTriggerSpell), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell TrailOfLight = new Spell("Trail of Light", ClassType.Priest, ClassSpec.HolyPriest, new[] { 200128 }, new[] { 1 }, 2, 1022951, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
    }
}