namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Marksmanship : Hunter
    {
        public Spell AMurderOfCrows = new Spell("A Murder of Crows", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 131894 }, new[] { 1 }, 3, 645217, new double[] { 0 }, new double[] { 15 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy) });
        public Spell AimedShot = new Spell("Aimed Shot", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 19434 }, new[] { 10 }, 0, 135130, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell ArcaneShot = new Spell("Arcane Shot", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 321293 }, new[] { 14 }, 0, 461846, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell Barrage = new Spell("Barrage", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 120360 }, new[] { 1 }, 5, 236201, new double[] { 0 }, new double[] { 3 }, false, 40, new[] { "Direct Damage (AE-Chain) - Ability" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicTriggerSpell) });
        public Spell BindingShackles = new Spell("Binding Shackles", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 321468 }, new[] { 1 }, 15, 463560, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell BindingShot = new Spell("Binding Shot", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 109248 }, new[] { 33 }, 0, 462650, new double[] { 0 }, new double[] { 10 }, false, 30, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.CreateAreaTrigger, EffectAuraType.None), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell BurstingShot = new Spell("Bursting Shot", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 186387 }, new[] { 12 }, 0, 1376038, new double[] { 0 }, new double[] { 6 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDecreaseSpeed), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.KnockBack, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell CallingTheShots = new Spell("Calling the Shots", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 260404 }, new[] { 1 }, 19, 236173, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell CarefulAim = new Spell("Careful Aim", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 260228 }, new[] { 1 }, 4, 132217, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ChimaeraShot = new Spell("Chimaera Shot", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 342049 }, new[] { 0 }, 12, 236176, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell ConcussiveShot = new Spell("Concussive Shot", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 5116, 321023 }, new[] { 13 }, 0, 135860, new double[] { 0 }, new double[] { 6 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDecreaseSpeed) });
        public Spell CounterShot = new Spell("Counter Shot", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 147362 }, new[] { 18 }, 0, 249170, new double[] { 0 }, new double[] { 3 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.InterruptCast, EffectAuraType.None) });
        public Spell DeadEye = new Spell("Dead Eye", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 321460 }, new[] { 1 }, 17, 1033497, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxCharges), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell DoubleTap = new Spell("Double Tap", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 260402 }, new[] { 0 }, 18, 537468, new double[] { 0 }, new double[] { 15 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Exhilaration = new Spell("Exhilaration", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 231546 }, new[] { 44 }, 0, 461117, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ExplosiveShot = new Spell("Explosive Shot", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 212431 }, new[] { 1 }, 6, 236178, new double[] { 0 }, new double[] { 3 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy) });
        public Spell LethalShots = new Spell("Lethal Shots", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 260393 }, new[] { 1 }, 16, 461120, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell LockAndLoad = new Spell("Lock and Load", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 194595 }, new[] { 1 }, 20, 236185, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell LoneWolf = new Spell("Lone Wolf", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 155228 }, new[] { 24 }, 0, 1033494, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MasterMarksman = new Spell("Master Marksman", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 260309 }, new[] { 1 }, 1, 132177, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MasterySniperTraining = new Spell("Mastery: Sniper Training", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 193468 }, new[] { 10 }, 0, 236203, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.HasteRanged) });
        public Spell Multi_Shot = new Spell("Multi-Shot", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 257620 }, new[] { 23 }, 0, 132330, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell PreciseShots = new Spell("Precise Shots", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 260240 }, new[] { 38 }, 0, 236179, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell RapidFire = new Spell("Rapid Fire", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 257044, 321281 }, new[] { 20, 28 }, 0, 461115, new double[] { 0 }, new double[] { 2 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell SerpentSting = new Spell("Serpent Sting", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 271788 }, new[] { 0 }, 2, 1033905, new double[] { 0 }, new double[] { 18 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell SteadyFocus = new Spell("Steady Focus", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 193533 }, new[] { 1 }, 10, 236182, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SteadyShot = new Spell("Steady Shot", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 321018 }, new[] { 11 }, 0, 236182, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell Streamline = new Spell("Streamline", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 260367 }, new[] { 1 }, 11, 132208, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell TrickShots = new Spell("Trick Shots", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 257621 }, new[] { 32 }, 0, 2065591, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell TrueAim = new Spell("True Aim", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 321287 }, new[] { 49 }, 0, 1604164, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell Trueshot = new Spell("Trueshot", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 288613 }, new[] { 34 }, 0, 132329, new double[] { 0 }, new double[] { 15 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AbilityPeriodicCrit), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModPowerRegenPercent), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModRuneRegenSpeed), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.RetainComboPoints), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Volley = new Spell("Volley", ClassType.Hunter, ClassSpec.Marksmanship, new[] { 260243 }, new[] { 1 }, 21, 132205, new double[] { 0 }, new double[] { 6 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
    }
}