namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Mistweaver : Monk
    {
        public Spell Detox = new Spell("Detox", ClassType.Monk, ClassSpec.Mistweaver, new[] { 115450 }, new[] { 24 }, 0, 460692, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dispel, EffectAuraType.None) });
        public Spell EnvelopingBreath = new Spell("Enveloping Breath", ClassType.Monk, ClassSpec.Mistweaver, new[] { 343655 }, new[] { 58 }, 0, 574571, new double[] { }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell EnvelopingMist = new Spell("Enveloping Mist", ClassType.Monk, ClassSpec.Mistweaver, new[] { 124682, 231605 }, new[] { 12, 38 }, 0, 775461, new double[] { 0 }, new double[] { 6 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModHealingReceived), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicHeal), new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None) });
        public Spell EssenceFont = new Spell("Essence Font", ClassType.Monk, ClassSpec.Mistweaver, new[] { 191837, 231633 }, new[] { 21, 34 }, 0, 1360978, new double[] { 0 }, new double[] { 3 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicTriggerSpell) });
        public Spell ExpelHarm = new Spell("Expel Harm", ClassType.Monk, ClassSpec.Mistweaver, new[] { 322104, 325214 }, new[] { 43, 54 }, 0, 627486, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell FocusedThunder = new Spell("Focused Thunder", ClassType.Monk, ClassSpec.Mistweaver, new[] { 197895 }, new[] { 0 }, 19, 839394, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell FortifyingBrew = new Spell("Fortifying Brew", ClassType.Monk, ClassSpec.Mistweaver, new[] { 243435, 325208 }, new[] { 28, 48 }, 0, 615341, new double[] { 0 }, new double[] { 15 }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModIncreaseHealthPercent), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModScale) });
        public Spell HealingElixir = new Spell("Healing Elixir", ClassType.Monk, ClassSpec.Mistweaver, new[] { 122281 }, new[] { 1 }, 13, 608939, new double[] { }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.HealPct, EffectAuraType.None) });
        public Spell InvokeChi_JiTheRedCrane = new Spell("Invoke Chi-Ji, the Red Crane", ClassType.Monk, ClassSpec.Mistweaver, new[] { 325197 }, new[] { 1 }, 18, 877514, new double[] { 0 }, new double[] { 25 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None) });
        public Spell InvokeYulonTheJadeSerpent = new Spell("Invoke Yu'lon, the Jade Serpent", ClassType.Monk, ClassSpec.Mistweaver, new[] { 322118 }, new[] { 42 }, 0, 574571, new double[] { 0 }, new double[] { 25 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None) });
        public Spell LeatherSpecialization = new Spell("Leather Specialization", ClassType.Monk, ClassSpec.Mistweaver, new[] { 120224 }, new[] { 27 }, 0, 132646, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModTotalStatPercentage) });
        public Spell LifeCoccoon = new Spell("Life Coccoon", ClassType.Monk, ClassSpec.Mistweaver, new[] { 343744 }, new[] { 41 }, 0, 627485, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell LifeCocoon = new Spell("Life Cocoon", ClassType.Monk, ClassSpec.Mistweaver, new[] { 116849 }, new[] { 27 }, 0, 627485, new double[] { 0 }, new double[] { 12 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, (EffectAuraType)259), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.SchoolAbsorb), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Lifecycles = new Spell("Lifecycles", ClassType.Monk, ClassSpec.Mistweaver, new[] { 197915 }, new[] { 0 }, 7, 988198, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ManaTea = new Spell("Mana Tea", ClassType.Monk, ClassSpec.Mistweaver, new[] { 197908 }, new[] { 0 }, 9, 608949, new double[] { 0 }, new double[] { 10 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModPowerCostSchoolPct) });
        public Spell MasteryGustOfMists = new Spell("Mastery: Gust of Mists", ClassType.Monk, ClassSpec.Mistweaver, new[] { 117907 }, new[] { 10 }, 0, 988198, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MistWrap = new Spell("Mist Wrap", ClassType.Monk, ClassSpec.Mistweaver, new[] { 197900 }, new[] { 0 }, 1, 988196, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell RefreshingJadeWind = new Spell("Refreshing Jade Wind", ClassType.Monk, ClassSpec.Mistweaver, new[] { 196725 }, new[] { 1 }, 17, 606549, new double[] { 0 }, new double[] { 9 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicTriggerSpell), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell RenewingMist = new Spell("Renewing Mist", ClassType.Monk, ClassSpec.Mistweaver, new[] { 115151, 281231 }, new[] { 18, 29 }, 0, 627487, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxCharges), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Revival = new Spell("Revival", ClassType.Monk, ClassSpec.Mistweaver, new[] { 115310 }, new[] { 46 }, 0, 1020466, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dispel, EffectAuraType.None), new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None) });
        public Spell RisingMist = new Spell("Rising Mist", ClassType.Monk, ClassSpec.Mistweaver, new[] { 274909 }, new[] { 0 }, 21, 1360977, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell RisingSunKick = new Spell("Rising Sun Kick", ClassType.Monk, ClassSpec.Mistweaver, new[] { 107428, 262840 }, new[] { 10, 26 }, 0, 642415, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell SongOfChi_Ji = new Spell("Song of Chi-Ji", ClassType.Monk, ClassSpec.Mistweaver, new[] { 198898 }, new[] { 1 }, 11, 332402, new double[] { 0 }, new double[] { 5 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.CreateAreaTrigger, EffectAuraType.None) });
        public Spell SoothingMist = new Spell("Soothing Mist", ClassType.Monk, ClassSpec.Mistweaver, new[] { 115175 }, new[] { 17 }, 0, 606550, new double[] { 0 }, new double[] { 8 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicHeal) });
        public Spell SpiritOfTheCrane = new Spell("Spirit of the Crane", ClassType.Monk, ClassSpec.Mistweaver, new[] { 210802 }, new[] { 1 }, 8, 977169, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SummonJadeSerpentStatue = new Spell("Summon Jade Serpent Statue", ClassType.Monk, ClassSpec.Mistweaver, new[] { 115313 }, new[] { 1 }, 16, 620831, new double[] { 0 }, new double[] { 900 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None) });
        public Spell TeachingsOfTheMonastery = new Spell("Teachings of the Monastery", ClassType.Monk, ClassSpec.Mistweaver, new[] { 116645 }, new[] { 19 }, 0, 611422, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ThunderFocusTea = new Spell("Thunder Focus Tea", ClassType.Monk, ClassSpec.Mistweaver, new[] { 116680, 231876 }, new[] { 23, 33 }, 0, 611418, new double[] { 0 }, new double[] { 30 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell TouchOfDeath = new Spell("Touch of Death", ClassType.Monk, ClassSpec.Mistweaver, new[] { 344360 }, new[] { 52 }, 0, 606552, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Vivify = new Spell("Vivify", ClassType.Monk, ClassSpec.Mistweaver, new[] { 274586 }, new[] { 37 }, 0, 1360980, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
    }
}