namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Outlaw : Rogue
    {
        public Spell AcrobaticStrikes = new Spell("Acrobatic Strikes", ClassType.Rogue, ClassSpec.Outlaw, new[] { 196924 }, new[] { 0 }, 4, 589068, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, (EffectAuraType)153), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell AdrenalineRush = new Spell("Adrenaline Rush", ClassType.Rogue, ClassSpec.Outlaw, new[] { 13750 }, new[] { 42 }, 0, 136206, new double[] { 0 }, new double[] { 20 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentDone), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxPower), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMeleeRangedHaste2), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModPowerRegenPercent) });
        public Spell Alacrity = new Spell("Alacrity", ClassType.Rogue, ClassSpec.Outlaw, new[] { 193539 }, new[] { 0 }, 17, 571558, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell BetweenTheEyes = new Spell("Between the Eyes", ClassType.Rogue, ClassSpec.Outlaw, new[] { 235484, 315341 }, new[] { 17, 44 }, 0, 135610, new double[] { 0 }, new double[] { 0 }, false, 20, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, (EffectAuraType)306), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell BladeFlurry = new Spell("Blade Flurry", ClassType.Rogue, ClassSpec.Outlaw, new[] { 13877, 331851 }, new[] { 19, 52 }, 0, 132350, new double[] { 0 }, new double[] { 12 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell BladeRush = new Spell("Blade Rush", ClassType.Rogue, ClassSpec.Outlaw, new[] { 271877 }, new[] { 0 }, 20, 1016243, new double[] { 0 }, new double[] { }, false, 20, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell BlindingPowder = new Spell("Blinding Powder", ClassType.Rogue, ClassSpec.Outlaw, new[] { 256165 }, new[] { 0 }, 14, 133592, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell CombatPotency = new Spell("Combat Potency", ClassType.Rogue, ClassSpec.Outlaw, new[] { 35551, 61329 }, new[] { 37, 43 }, 0, 135673, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModPowerRegenPercent), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell DancingSteel = new Spell("Dancing Steel", ClassType.Rogue, ClassSpec.Outlaw, new[] { 272026 }, new[] { 0 }, 19, 132350, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ChargeRecoveryMultiplier) });
        public Spell DirtyTricks = new Spell("Dirty Tricks", ClassType.Rogue, ClassSpec.Outlaw, new[] { 108216 }, new[] { 0 }, 13, 460691, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell Dispatch = new Spell("Dispatch", ClassType.Rogue, ClassSpec.Outlaw, new[] { 2098 }, new[] { 22 }, 0, 236286, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Dreadblades = new Spell("Dreadblades", ClassType.Rogue, ClassSpec.Outlaw, new[] { 343142 }, new[] { 0 }, 18, 1301078, new double[] { 0 }, new double[] { 10 }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Evasion = new Spell("Evasion", ClassType.Rogue, ClassSpec.Outlaw, new[] { 344363 }, new[] { 58 }, 0, 136205, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell GhostlyStrike = new Spell("Ghostly Strike", ClassType.Rogue, ClassSpec.Outlaw, new[] { 196937 }, new[] { 1 }, 3, 132094, new double[] { 0 }, new double[] { 10 }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.SchoolMaskDamageFromCaster), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Gouge = new Spell("Gouge", ClassType.Rogue, ClassSpec.Outlaw, new[] { 1776 }, new[] { 46 }, 0, 132155, new double[] { 15 }, new double[] { 4 }, false, 5, new[] { "Mez" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModStun), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None) });
        public Spell GrapplingHook = new Spell("Grappling Hook", ClassType.Rogue, ClassSpec.Outlaw, new[] { 195457, 319600 }, new[] { 18, 56 }, 0, 1373906, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell HitAndRun = new Spell("Hit and Run", ClassType.Rogue, ClassSpec.Outlaw, new[] { 196922 }, new[] { 0 }, 6, 132296, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModSpeedAlways) });
        public Spell IronStomach = new Spell("Iron Stomach", ClassType.Rogue, ClassSpec.Outlaw, new[] { 193546 }, new[] { 0 }, 10, 237415, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell KillingSpree = new Spell("Killing Spree", ClassType.Rogue, ClassSpec.Outlaw, new[] { 51690 }, new[] { 1 }, 21, 236277, new double[] { 0 }, new double[] { 2 }, false, 10, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AllowOnlyAbility), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell LoadedDice = new Spell("Loaded Dice", ClassType.Rogue, ClassSpec.Outlaw, new[] { 256170 }, new[] { 0 }, 16, 1373910, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell MasteryMainGauche = new Spell("Mastery: Main Gauche", ClassType.Rogue, ClassSpec.Outlaw, new[] { 76806 }, new[] { 10 }, 0, 135651, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell PistolShot = new Spell("Pistol Shot", ClassType.Rogue, ClassSpec.Outlaw, new[] { 185763 }, new[] { 12 }, 0, 1373908, new double[] { 0 }, new double[] { 6 }, false, 20, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDecreaseSpeed), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell QuickDraw = new Spell("Quick Draw", ClassType.Rogue, ClassSpec.Outlaw, new[] { 196938 }, new[] { 0 }, 2, 331438, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell RestlessBlades = new Spell("Restless Blades", ClassType.Rogue, ClassSpec.Outlaw, new[] { 79096 }, new[] { 41 }, 0, 458731, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell RetractableHook = new Spell("Retractable Hook", ClassType.Rogue, ClassSpec.Outlaw, new[] { 256188 }, new[] { 0 }, 5, 1373906, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell RollTheBones = new Spell("Roll the Bones", ClassType.Rogue, ClassSpec.Outlaw, new[] { 315508 }, new[] { 29 }, 0, 1373910, new double[] { 0 }, new double[] { 30 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Ruthlessness = new Spell("Ruthlessness", ClassType.Rogue, ClassSpec.Outlaw, new[] { 14161 }, new[] { 27 }, 0, 132122, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SinisterStrike = new Spell("Sinister Strike", ClassType.Rogue, ClassSpec.Outlaw, new[] { 193315, 279876 }, new[] { 10, 12 }, 0, 136189, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Weaponmaster = new Spell("Weaponmaster", ClassType.Rogue, ClassSpec.Outlaw, new[] { 200733 }, new[] { 0 }, 1, 1035036, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
    }
}