namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class ProtectionWarrior : Warrior
    {
        public Spell AngerManagement = new Spell("Anger Management", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 152278 }, new[] { 0 }, 19, 971080, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Avatar = new Spell("Avatar", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 107574, 316438 }, new[] { 32, 52 }, 0, 613534, new double[] { 0 }, new double[] { 20 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAutoattackDamage), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModScale), new SpellEffectData(SpellEffectName.ApplyAuraOnPet, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.ScriptEffect, EffectAuraType.None) });
        public Spell BestServedCold = new Spell("Best Served Cold", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 202560 }, new[] { 0 }, 7, 132353, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell Bolster = new Spell("Bolster", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 280001 }, new[] { 0 }, 21, 951821, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell BoomingVoice = new Spell("Booming Voice", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 202743 }, new[] { 0 }, 8, 132339, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell CracklingThunder = new Spell("Crackling Thunder", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 203201 }, new[] { 0 }, 10, 839979, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell DeepWounds = new Spell("Deep Wounds", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 115768 }, new[] { 42 }, 0, 132090, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell DemoralizingShout = new Spell("Demoralizing Shout", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 1160, 316464 }, new[] { 27, 49 }, 0, 132366, new double[] { 0 }, new double[] { 8 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentDone), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModIgnoreTargetResist), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMeleeDamageFromCaster), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModSpellDamageFromCaster), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None) });
        public Spell Devastate = new Spell("Devastate", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 20243 }, new[] { 14 }, 0, 135291, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell DragonRoar = new Spell("Dragon Roar", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 118000 }, new[] { 1 }, 9, 642418, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Execute = new Spell("Execute", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 231830, 316405 }, new[] { 13, 18 }, 0, 135358, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell HeavyRepercussions = new Spell("Heavy Repercussions", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 203177 }, new[] { 0 }, 20, 134977, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell IgnorePain = new Spell("Ignore Pain", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 316778 }, new[] { 29 }, 0, 1377132, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell ImpendingVictory = new Spell("Impending Victory", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 202168 }, new[] { 0 }, 15, 589768, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Indomitable = new Spell("Indomitable", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 202095 }, new[] { 0 }, 14, 236310, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModIncreaseHealthPercent) });
        public Spell IntoTheFray = new Spell("Into the Fray", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 202603 }, new[] { 0 }, 16, 132334, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy) });
        public Spell LastStand = new Spell("Last Stand", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 12975 }, new[] { 38 }, 0, 135871, new double[] { 20 }, new double[] { 15 }, false, 0, new[] { "Temporary Health" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModIncreaseHealthPercent), new SpellEffectData(SpellEffectName.HealPct, EffectAuraType.None) });
        public Spell MasteryCriticalBlock = new Spell("Mastery: Critical Block", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 76857 }, new[] { 10 }, 0, 236307, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAttackPowerPct), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModBlockCritChance), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModBlockPercent) });
        public Spell Menace = new Spell("Menace", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 275338 }, new[] { 0 }, 12, 132154, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.OverrideActionbarSpells) });
        public Spell NeverSurrender = new Spell("Never Surrender", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 202561 }, new[] { 0 }, 13, 999950, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Punish = new Spell("Punish", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 275334 }, new[] { 0 }, 2, 458719, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Ravager = new Spell("Ravager", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 228920 }, new[] { 0 }, 18, 970854, new double[] { 0 }, new double[] { 12 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Revenge = new Spell("Revenge", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 6572 }, new[] { 12 }, 0, 132353, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Riposte = new Spell("Riposte", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 161798 }, new[] { 42 }, 0, 135340, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ConvertCritRatingPctToParryRating) });
        public Spell RumblingEarth = new Spell("Rumbling Earth", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 275339 }, new[] { 0 }, 5, 451165, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ShieldSlam = new Spell("Shield Slam", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 231834, 316523, 316790 }, new[] { 10, 28, 44 }, 0, 134951, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ShieldWall = new Spell("Shield Wall", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 871, 316834 }, new[] { 23, 58 }, 0, 132362, new double[] { 0 }, new double[] { 8 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken) });
        public Spell Shockwave = new Spell("Shockwave", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 46968 }, new[] { 21 }, 0, 236312, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None), new SpellEffectData(SpellEffectName.ScriptEffect, EffectAuraType.None) });
        public Spell StormBolt = new Spell("Storm Bolt", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 107570 }, new[] { 0 }, 6, 613535, new double[] { 0 }, new double[] { }, false, 20, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell ThunderClap = new Spell("Thunder Clap", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 6343, 316414 }, new[] { 19, 37 }, 0, 136105, new double[] { 0 }, new double[] { 10 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDecreaseSpeed), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell UnstoppableForce = new Spell("Unstoppable Force", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 275336 }, new[] { 0 }, 17, 458976, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell Vanguard = new Spell("Vanguard", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 71, 316428 }, new[] { 20, 48 }, 0, 132341, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, (EffectAuraType)268), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModTotalStatPercentage) });
        public Spell WarMachine = new Spell("War Machine", ClassType.Warrior, ClassSpec.ProtectionWarrior, new[] { 316733 }, new[] { 0 }, 1, 132205, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModRageFromDamageDealt), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
    }
}