namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class ProtectionPaladin : Paladin
    {
        public Spell ArdentDefender = new Spell("Ardent Defender", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 31850 }, new[] { 42 }, 0, 135870, new double[] { 0 }, new double[] { 8 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicHaste) });
        public Spell AvengersShield = new Spell("Avenger's Shield", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 31935, 231665 }, new[] { 10, 44 }, 0, 135874, new double[] { 0 }, new double[] { 3 }, false, 30, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModSilence), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.InterruptCast, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell BlessedHammer = new Spell("Blessed Hammer", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 204019, 229976 }, new[] { 0, 1 }, 3, 535595, new double[] { 0 }, new double[] { 5 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.SchoolAbsorb), new SpellEffectData(SpellEffectName.CreateAreaTrigger, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None) });
        public Spell BlessingOfSpellwarding = new Spell("Blessing of Spellwarding", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 204018 }, new[] { 1 }, 12, 135880, new double[] { 0 }, new double[] { 10 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.SchoolImmunity) });
        public Spell CleanseToxins = new Spell("Cleanse Toxins", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 213644 }, new[] { 12 }, 0, 135953, new double[] { 8 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dispel, EffectAuraType.None) });
        public Spell ConsecratedGround = new Spell("Consecrated Ground", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 204054 }, new[] { 1 }, 17, 236260, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell Consecration = new Spell("Consecration", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 327980, 344172 }, new[] { 18, 23 }, 0, 135926, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell CrusaderStrike = new Spell("Crusader Strike", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 342348 }, new[] { 11 }, 0, 135891, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell CrusadersJudgment = new Spell("Crusader's Judgment", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 204023 }, new[] { 1 }, 5, 236251, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxCharges) });
        public Spell DivineProtection = new Spell("Divine Protection", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 498 }, new[] { 26 }, 0, 524353, new double[] { 0 }, new double[] { 8 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken) });
        public Spell FinalStand = new Spell("Final Stand", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 204077 }, new[] { 1 }, 21, 135889, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell FirstAvenger = new Spell("First Avenger", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 203776 }, new[] { 0 }, 4, 1029590, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell GrandCrusader = new Spell("Grand Crusader", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 85043 }, new[] { 27 }, 0, 133176, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell GuardianOfAncientKings = new Spell("Guardian of Ancient Kings", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 86659 }, new[] { 39 }, 0, 135919, new double[] { 0 }, new double[] { 8 }, false, 30, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Transform) });
        public Spell HammerOfTheRighteous = new Spell("Hammer of the Righteous", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 53595, 317854 }, new[] { 14, 33 }, 0, 236253, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxCharges), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell HandOfTheProtector = new Spell("Hand of the Protector", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 315924 }, new[] { 0 }, 16, 236248, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Judgment = new Spell("Judgment", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 231663, 275779, 315867 }, new[] { 3, 16, 29 }, 0, 135959, new double[] { 0 }, new double[] { }, false, 30, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell JudgmentOfLight = new Spell("Judgment of Light", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 183778 }, new[] { 1 }, 18, 237541, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell JudgmentsOfTheWise = new Spell("Judgments of the Wise", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 105424 }, new[] { 16 }, 0, 236255, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MasteryDivineBulwark = new Spell("Mastery: Divine Bulwark", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 76671, 317907 }, new[] { 10, 19 }, 0, 135923, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAttackPowerPct), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModBlockPercent) });
        public Spell MomentOfGlory = new Spell("Moment of Glory", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 327193 }, new[] { 1 }, 6, 589117, new double[] { 0 }, new double[] { 15 }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell Rebuke = new Spell("Rebuke", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 96231 }, new[] { 27 }, 0, 523893, new double[] { 15 }, new double[] { 4 }, false, 5, new[] { "Silence" }, new[] { new SpellEffectData(SpellEffectName.InterruptCast, EffectAuraType.None) });
        public Spell Redoubt = new Spell("Redoubt", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 280373 }, new[] { 0 }, 2, 132359, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell RighteousFury = new Spell("Righteous Fury", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 25780 }, new[] { 10 }, 0, 135962, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModThreat) });
        public Spell RighteousProtector = new Spell("Righteous Protector", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 204074 }, new[] { 1 }, 20, 236264, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Riposte = new Spell("Riposte", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 161800 }, new[] { 48 }, 0, 135340, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ConvertCritRatingPctToParryRating) });
        public Spell SanctifiedWrath = new Spell("Sanctified Wrath", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 171648 }, new[] { 0 }, 19, 236259, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Sanctuary = new Spell("Sanctuary", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 105805 }, new[] { 10 }, 0, 136051, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDodgePercent), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModExpertise) });
        public Spell ShiningLight = new Spell("Shining Light", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 321136 }, new[] { 48 }, 0, 1360764, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell WordOfGlory = new Spell("Word of Glory", ClassType.Paladin, ClassSpec.ProtectionPaladin, new[] { 315921 }, new[] { 34 }, 0, 133192, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
    }
}