namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class RestorationShaman : Shaman
    {
        public Spell AncestralProtectionTotem = new Spell("Ancestral Protection Totem", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 207399 }, new[] { 1 }, 12, 136080, new double[] { 0 }, new double[] { 30 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None) });
        public Spell AncestralVigor = new Spell("Ancestral Vigor", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 207401 }, new[] { 0 }, 10, 237574, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Ascendance = new Spell("Ascendance", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 114052 }, new[] { 50 }, 21, 135791, new double[] { 0 }, new double[] { 15 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Transform), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell ChainHeal = new Spell("Chain Heal", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 231780 }, new[] { 23 }, 0, 136042, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell Deluge = new Spell("Deluge", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 200076 }, new[] { 0 }, 5, 893777, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Downpour = new Spell("Downpour", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 207778 }, new[] { 0 }, 17, 1698701, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None) });
        public Spell EarthShield = new Spell("Earth Shield", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 974 }, new[] { 22 }, 0, 136089, new double[] { 0 }, new double[] { 600 }, false, 40, new[] { "Earth Shield" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModHealingReceived) });
        public Spell EarthenWallTotem = new Spell("Earthen Wall Totem", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 198838 }, new[] { 1 }, 11, 136098, new double[] { 0 }, new double[] { 15 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None) });
        public Spell EarthgrabTotem = new Spell("Earthgrab Totem", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 51485 }, new[] { 1 }, 8, 136100, new double[] { 0 }, new double[] { 20 }, false, 35, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None) });
        public Spell FlashFlood = new Spell("Flash Flood", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 280614 }, new[] { 0 }, 16, 135861, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell GracefulSpirit = new Spell("Graceful Spirit", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 192088 }, new[] { 0 }, 14, 237585, new double[] { }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell HealingRain = new Spell("Healing Rain", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 73920 }, new[] { 34 }, 0, 136037, new double[] { 0 }, new double[] { 10 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell HealingTideTotem = new Spell("Healing Tide Totem", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 108280, 343205 }, new[] { 49, 58 }, 0, 538569, new double[] { 0 }, new double[] { 10 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None) });
        public Spell HealingWave = new Spell("Healing Wave", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 77472 }, new[] { 27 }, 0, 136043, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None) });
        public Spell HighTide = new Spell("High Tide", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 157154 }, new[] { 1 }, 19, 971078, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell LavaBurst = new Spell("Lava Burst", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 51505, 231721 }, new[] { 11, 20 }, 0, 237582, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerMissile, EffectAuraType.None) });
        public Spell LavaSurge = new Spell("Lava Surge", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 77756 }, new[] { 29 }, 0, 451169, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ManaTideTotem = new Spell("Mana Tide Totem", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 16191, 343182 }, new[] { 38, 52 }, 0, 135861, new double[] { 0 }, new double[] { 8 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None) });
        public Spell MasteryDeepHealing = new Spell("Mastery: Deep Healing", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 77226 }, new[] { 10 }, 0, 136041, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, (EffectAuraType)354), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell PurifySpirit = new Spell("Purify Spirit", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 77130 }, new[] { 18 }, 0, 236288, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dispel, EffectAuraType.None) });
        public Spell Resurgence = new Spell("Resurgence", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 16196 }, new[] { 37 }, 0, 132315, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Riptide = new Spell("Riptide", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 61295 }, new[] { 10 }, 0, 252995, new double[] { 0 }, new double[] { 18 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicHeal), new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None) });
        public Spell SpiritLinkTotem = new Spell("Spirit Link Totem", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 98008 }, new[] { 43 }, 0, 237586, new double[] { 0 }, new double[] { 6 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None) });
        public Spell SpiritwalkersGrace = new Spell("Spiritwalker's Grace", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 79206 }, new[] { 44 }, 0, 451170, new double[] { 0 }, new double[] { 15 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.CastWhileWalking), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.HealAbsorbTest), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModSpeedAlways) });
        public Spell SurgeOfEarth = new Spell("Surge of Earth", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 320746 }, new[] { 0 }, 6, 2101174, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell TidalWaves = new Spell("Tidal Waves", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 51564, 231785 }, new[] { 20, 27 }, 0, 237590, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Torrent = new Spell("Torrent", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 200072 }, new[] { 0 }, 1, 252995, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell Undulation = new Spell("Undulation", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 200071 }, new[] { 0 }, 2, 136043, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell UnleashLife = new Spell("Unleash Life", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 73685 }, new[] { 12 }, 3, 462328, new double[] { 0 }, new double[] { 10 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Heal, EffectAuraType.None) });
        public Spell WaterShield = new Spell("Water Shield", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 52127 }, new[] { 41 }, 0, 132315, new double[] { 0 }, new double[] { 3600 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModPowerRegen), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Wellspring = new Spell("Wellspring", ClassType.Shaman, ClassSpec.RestorationShaman, new[] { 197995 }, new[] { 0 }, 20, 893778, new double[] { 0 }, new double[] { }, false, 30, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
    }
}