namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Subtlety : Rogue
    {
        public Spell Alacrity = new Spell("Alacrity", ClassType.Rogue, ClassSpec.Subtlety, new[] { 193539 }, new[] { 0 }, 17, 571558, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Backstab = new Spell("Backstab", ClassType.Rogue, ClassSpec.Subtlety, new[] { 53, 319949 }, new[] { 14, 46 }, 0, 132090, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell BlackPowder = new Spell("Black Powder", ClassType.Rogue, ClassSpec.Subtlety, new[] { 319175, 319178 }, new[] { 52, 58 }, 0, 608955, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell DarkShadow = new Spell("Dark Shadow", ClassType.Rogue, ClassSpec.Subtlety, new[] { 245687 }, new[] { 0 }, 16, 463284, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell DeepeningShadows = new Spell("Deepening Shadows", ClassType.Rogue, ClassSpec.Subtlety, new[] { 185314 }, new[] { 41 }, 0, 136223, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell EnvelopingShadows = new Spell("Enveloping Shadows", ClassType.Rogue, ClassSpec.Subtlety, new[] { 238104 }, new[] { 0 }, 18, 132291, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxCharges) });
        public Spell Eviscerate = new Spell("Eviscerate", ClassType.Rogue, ClassSpec.Subtlety, new[] { 231716 }, new[] { 44 }, 0, 132292, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell FindWeakness = new Spell("Find Weakness", ClassType.Rogue, ClassSpec.Subtlety, new[] { 316219 }, new[] { 37 }, 0, 132295, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Gloomblade = new Spell("Gloomblade", ClassType.Rogue, ClassSpec.Subtlety, new[] { 200758 }, new[] { 1 }, 3, 1035040, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell MasterOfShadows = new Spell("Master of Shadows", ClassType.Rogue, ClassSpec.Subtlety, new[] { 196976 }, new[] { 1 }, 19, 136129, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell MasteryExecutioner = new Spell("Mastery: Executioner", ClassType.Rogue, ClassSpec.Subtlety, new[] { 76808 }, new[] { 10 }, 0, 132397, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell NightTerrors = new Spell("Night Terrors", ClassType.Rogue, ClassSpec.Subtlety, new[] { 277953 }, new[] { 0 }, 14, 136194, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Premeditation = new Spell("Premeditation", ClassType.Rogue, ClassSpec.Subtlety, new[] { 343160 }, new[] { 0 }, 2, 136183, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell RelentlessStrikes = new Spell("Relentless Strikes", ClassType.Rogue, ClassSpec.Subtlety, new[] { 58423 }, new[] { 26 }, 0, 132340, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Rupture = new Spell("Rupture", ClassType.Rogue, ClassSpec.Subtlety, new[] { 1943 }, new[] { 17 }, 0, 132302, new double[] { 0 }, new double[] { 4 }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell SecretTechnique = new Spell("Secret Technique", ClassType.Rogue, ClassSpec.Subtlety, new[] { 280719 }, new[] { 0 }, 20, 132305, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell ShadowBlades = new Spell("Shadow Blades", ClassType.Rogue, ClassSpec.Subtlety, new[] { 121471 }, new[] { 42 }, 0, 376022, new double[] { 0 }, new double[] { 20 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ShadowDance = new Spell("Shadow Dance", ClassType.Rogue, ClassSpec.Subtlety, new[] { 185313 }, new[] { 22 }, 0, 236279, new double[] { 0 }, new double[] { 8 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAutoattackDamage), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModIgnoreShapeshift), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModTotalThreat), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ObsModHealth) });
        public Spell ShadowFocus = new Spell("Shadow Focus", ClassType.Rogue, ClassSpec.Subtlety, new[] { 108209 }, new[] { 0 }, 6, 571316, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ShadowTechniques = new Spell("Shadow Techniques", ClassType.Rogue, ClassSpec.Subtlety, new[] { 196912 }, new[] { 27 }, 0, 132299, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Shadowstep = new Spell("Shadowstep", ClassType.Rogue, ClassSpec.Subtlety, new[] { 36554 }, new[] { 18 }, 0, 132303, new double[] { 0 }, new double[] { 2 }, false, 25, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModIncreaseSpeed), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell Shadowstrike = new Spell("Shadowstrike", ClassType.Rogue, ClassSpec.Subtlety, new[] { 185438 }, new[] { 12 }, 0, 1373912, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell ShotInTheDark = new Spell("Shot in the Dark", ClassType.Rogue, ClassSpec.Subtlety, new[] { 257505 }, new[] { 0 }, 13, 132092, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ShurikenStorm = new Spell("Shuriken Storm", ClassType.Rogue, ClassSpec.Subtlety, new[] { 197835, 319951 }, new[] { 19, 56 }, 0, 1375677, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell ShurikenTornado = new Spell("Shuriken Tornado", ClassType.Rogue, ClassSpec.Subtlety, new[] { 277925 }, new[] { 0 }, 21, 236282, new double[] { 0 }, new double[] { 4 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicTriggerSpell) });
        public Spell ShurikenToss = new Spell("Shuriken Toss", ClassType.Rogue, ClassSpec.Subtlety, new[] { 114014 }, new[] { 16 }, 0, 135431, new double[] { 0 }, new double[] { }, false, 30, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell SoothingDarkness = new Spell("Soothing Darkness", ClassType.Rogue, ClassSpec.Subtlety, new[] { 200759 }, new[] { 0 }, 10, 136223, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell Sprint = new Spell("Sprint", ClassType.Rogue, ClassSpec.Subtlety, new[] { 245751 }, new[] { 43 }, 0, 132307, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell SymbolsOfDeath = new Spell("Symbols of Death", ClassType.Rogue, ClassSpec.Subtlety, new[] { 212283, 328077 }, new[] { 29, 43 }, 0, 252272, new double[] { }, new double[] { 10 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAutoattackDamage), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModCritPct), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None) });
        public Spell Weaponmaster = new Spell("Weaponmaster", ClassType.Rogue, ClassSpec.Subtlety, new[] { 193537 }, new[] { 0 }, 1, 1035036, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpellCopy) });
    }
}