using System;
using System.Collections.Generic;
using System.Text;

namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Survival : Hunter
    {
        public Spell AMurderOfCrows = new Spell("A Murder of Crows", ClassType.Hunter, ClassSpec.Survival, new[] { 131894 }, new[] { 1 }, 12, 645217, new double[] { 0 }, new double[] { 15 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy) });
        public Spell AlphaPredator = new Spell("Alpha Predator", ClassType.Hunter, ClassSpec.Survival, new[] { 269737 }, new[] { 0 }, 3, 1033484, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxCharges) });
        public Spell BirdsOfPrey = new Spell("Birds of Prey", ClassType.Hunter, ClassSpec.Survival, new[] { 260331 }, new[] { 1 }, 19, 612362, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell Butchery = new Spell("Butchery", ClassType.Hunter, ClassSpec.Survival, new[] { 212436 }, new[] { 1 }, 6, 999948, new double[] { 0 }, new double[] { }, false, 8, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Carve = new Spell("Carve", ClassType.Hunter, ClassSpec.Survival, new[] { 187708, 294029 }, new[] { 23, 32 }, 0, 1376039, new double[] { 0 }, new double[] { }, false, 8, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Chakrams = new Spell("Chakrams", ClassType.Hunter, ClassSpec.Survival, new[] { 259391 }, new[] { 1 }, 21, 648707, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell Exhilaration = new Spell("Exhilaration", ClassType.Hunter, ClassSpec.Survival, new[] { 231546 }, new[] { 44 }, 0, 461117, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell FlankingStrike = new Spell("Flanking Strike", ClassType.Hunter, ClassSpec.Survival, new[] { 269751 }, new[] { 0 }, 18, 236184, new double[] { 0 }, new double[] { }, false, 15, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell GuerrillaTactics = new Spell("Guerrilla Tactics", ClassType.Hunter, ClassSpec.Survival, new[] { 264332 }, new[] { 1 }, 4, 451164, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxCharges) });
        public Spell Harpoon = new Spell("Harpoon", ClassType.Hunter, ClassSpec.Survival, new[] { 190925, 231550 }, new[] { 14, 38 }, 0, 1376040, new double[] { 1 }, new double[] { 3 }, false, 30, new[] { "Class - Hunter - Harpoon/Disengage Shared" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ChargeRecoveryMod), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModRoot2), new SpellEffectData(SpellEffectName.TriggerMissile, EffectAuraType.None) });
        public Spell HydrasBite = new Spell("Hydra's Bite", ClassType.Hunter, ClassSpec.Survival, new[] { 260241 }, new[] { 1 }, 5, 2065587, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell KillCommand = new Spell("Kill Command", ClassType.Hunter, ClassSpec.Survival, new[] { 259489, 263186 }, new[] { 11, 28 }, 0, 132176, new double[] { 0 }, new double[] { }, false, 50, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell KillShot = new Spell("Kill Shot", ClassType.Hunter, ClassSpec.Survival, new[] { 320976 }, new[] { 42 }, 0, 236174, new double[] { 0 }, new double[] { }, false, 40, new[] { "Kill Shot" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell MongooseBite = new Spell("Mongoose Bite", ClassType.Hunter, ClassSpec.Survival, new[] { 259387 }, new[] { 1 }, 17, 1376044, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell Muzzle = new Spell("Muzzle", ClassType.Hunter, ClassSpec.Survival, new[] { 187707 }, new[] { 18 }, 0, 1376045, new double[] { 15 }, new double[] { 3 }, false, 5, new[] { "Silence" }, new[] { new SpellEffectData(SpellEffectName.InterruptCast, EffectAuraType.None) });
        public Spell RaptorStrike = new Spell("Raptor Strike", ClassType.Hunter, ClassSpec.Survival, new[] { 186270 }, new[] { 10 }, 0, 1376046, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell SerpentSting = new Spell("Serpent Sting", ClassType.Hunter, ClassSpec.Survival, new[] { 259491 }, new[] { 12 }, 0, 1033905, new double[] { 0 }, new double[] { 12 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDamage), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell SteelTrap = new Spell("Steel Trap", ClassType.Hunter, ClassSpec.Survival, new[] { 162488 }, new[] { 1 }, 11, 1467588, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.TriggerMissile, EffectAuraType.None) });
        public Spell TermsOfEngagement = new Spell("Terms of Engagement", ClassType.Hunter, ClassSpec.Survival, new[] { 265895 }, new[] { 0 }, 2, 1376040, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell TipOfTheSpear = new Spell("Tip of the Spear", ClassType.Hunter, ClassSpec.Survival, new[] { 260285 }, new[] { 1 }, 16, 1117879, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell VipersVenom = new Spell("Viper's Venom", ClassType.Hunter, ClassSpec.Survival, new[] { 268501 }, new[] { 0 }, 1, 236200, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell WildfireBomb = new Spell("Wildfire Bomb", ClassType.Hunter, ClassSpec.Survival, new[] { 259495 }, new[] { 20 }, 0, 2065634, new double[] { 0 }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.TriggerMissile, EffectAuraType.None) });
        public Spell WildfireBombs = new Spell("Wildfire Bombs", ClassType.Hunter, ClassSpec.Survival, new[] { 321290 }, new[] { 49 }, 0, 2115301, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell WildfireInfusion = new Spell("Wildfire Infusion", ClassType.Hunter, ClassSpec.Survival, new[] { 271014 }, new[] { 0 }, 20, 915852, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell WingClip = new Spell("Wing Clip", ClassType.Hunter, ClassSpec.Survival, new[] { 321026 }, new[] { 13 }, 0, 132215, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
    }
}