namespace WeakAuraAutomationTool.Warcraft.Classes
{
    public class Windwalker : Monk
    {
        public Spell Afterlife = new Spell("Afterlife", ClassType.Monk, ClassSpec.Windwalker, new[] { 116092, 322719 }, new[] { 38, 46 }, 0, 537227, new double[] { }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell BlackoutKick = new Spell("Blackout Kick", ClassType.Monk, ClassSpec.Windwalker, new[] { 261916, 261917 }, new[] { 17, 23 }, 0, 574575, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell CombatConditioning = new Spell("Combat Conditioning", ClassType.Monk, ClassSpec.Windwalker, new[] { 128595 }, new[] { 14 }, 0, 136001, new double[] { }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell ComboBreaker = new Spell("Combo Breaker", ClassType.Monk, ClassSpec.Windwalker, new[] { 137384 }, new[] { 19 }, 0, 572033, new double[] { 0 }, new double[] { }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell CycloneStrikes = new Spell("Cyclone Strikes", ClassType.Monk, ClassSpec.Windwalker, new[] { 220357 }, new[] { 19 }, 0, 606543, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell DanceOfChi_Ji = new Spell("Dance of Chi-Ji", ClassType.Monk, ClassSpec.Windwalker, new[] { 325201 }, new[] { 0 }, 18, 606543, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ProcTriggerSpell) });
        public Spell Disable = new Spell("Disable", ClassType.Monk, ClassSpec.Windwalker, new[] { 116095, 343731 }, new[] { 34, 41 }, 0, 132316, new double[] { 0 }, new double[] { 15 }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDecreaseSpeed), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy) });
        public Spell EnergizingElixir = new Spell("Energizing Elixir", ClassType.Monk, ClassSpec.Windwalker, new[] { 115288 }, new[] { 1 }, 9, 608938, new double[] { 0 }, new double[] { 5 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModPowerRegen), new SpellEffectData(SpellEffectName.Energize, EffectAuraType.None) });
        public Spell ExpelHarm = new Spell("Expel Harm", ClassType.Monk, ClassSpec.Windwalker, new[] { 322106 }, new[] { 43 }, 0, 627486, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier) });
        public Spell FistOfTheWhiteTiger = new Spell("Fist of the White Tiger", ClassType.Monk, ClassSpec.Windwalker, new[] { 261947 }, new[] { 0 }, 8, 2065583, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell FistsOfFury = new Spell("Fists of Fury", ClassType.Monk, ClassSpec.Windwalker, new[] { 113656 }, new[] { 12 }, 0, 627606, new double[] { 0 }, new double[] { 4 }, false, 8, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModParryPercent), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None), new SpellEffectData(SpellEffectName.SchoolDamage, EffectAuraType.None) });
        public Spell FlyingSerpentKick = new Spell("Flying Serpent Kick", ClassType.Monk, ClassSpec.Windwalker, new[] { 101545, 344487 }, new[] { 21, 54 }, 0, 606545, new double[] { 0 }, new double[] { 1.5 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMinimumSpeed), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModPacifySilence), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModSpeedNoControl), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.OverrideActionbarSpells), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.UseNormalMovementSpeed), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.WaterWalk) });
        public Spell FortifyingBrew = new Spell("Fortifying Brew", ClassType.Monk, ClassSpec.Windwalker, new[] { 243435, 325208 }, new[] { 28, 48 }, 0, 615341, new double[] { 0 }, new double[] { 15 }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddFlatModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModDamagePercentTaken), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModIncreaseHealthPercent), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModScale) });
        public Spell GoodKarma = new Spell("Good Karma", ClassType.Monk, ClassSpec.Windwalker, new[] { 280195 }, new[] { 1 }, 11, 651728, new double[] { }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell HitCombo = new Spell("Hit Combo", ClassType.Monk, ClassSpec.Windwalker, new[] { 196740 }, new[] { 0 }, 16, 574573, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell InvokeXuenTheWhiteTiger = new Spell("Invoke Xuen, the White Tiger", ClassType.Monk, ClassSpec.Windwalker, new[] { 123904, 323999 }, new[] { 42, 58 }, 0, 620832, new double[] { 0 }, new double[] { 24 }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.Summon, EffectAuraType.None) });
        public Spell LeatherSpecialization = new Spell("Leather Specialization", ClassType.Monk, ClassSpec.Windwalker, new[] { 120227 }, new[] { 27 }, 0, 132721, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModTotalStatPercentage) });
        public Spell MasteryComboStrikes = new Spell("Mastery: Combo Strikes", ClassType.Monk, ClassSpec.Windwalker, new[] { 115636 }, new[] { 10 }, 0, 609882, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell RisingSunKick = new Spell("Rising Sun Kick", ClassType.Monk, ClassSpec.Windwalker, new[] { 107428, 262840 }, new[] { 10, 26 }, 0, 642415, new double[] { 0 }, new double[] { }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.TriggerSpell, EffectAuraType.None) });
        public Spell RushingJadeWind = new Spell("Rushing Jade Wind", ClassType.Monk, ClassSpec.Windwalker, new[] { 116847 }, new[] { 1 }, 17, 606549, new double[] { 0 }, new double[] { 6 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicTriggerSpell), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Serenity = new Spell("Serenity", ClassType.Monk, ClassSpec.Windwalker, new[] { 152173 }, new[] { 0 }, 21, 988197, new double[] { 0 }, new double[] { 12 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAutoattackDamage), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModHealingDonePercent), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModResistanceExclusive), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.RetainComboPoints) });
        public Spell SpearHandStrike = new Spell("Spear Hand Strike", ClassType.Monk, ClassSpec.Windwalker, new[] { 116705 }, new[] { 18 }, 0, 608940, new double[] { 0 }, new double[] { 4 }, false, 5, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.InterruptCast, EffectAuraType.None) });
        public Spell SpinningCraneKick = new Spell("Spinning Crane Kick", ClassType.Monk, ClassSpec.Windwalker, new[] { 343730 }, new[] { 33 }, 0, 1360980, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell SpiritualFocus = new Spell("Spiritual Focus", ClassType.Monk, ClassSpec.Windwalker, new[] { 280197 }, new[] { 1 }, 19, 136038, new double[] { }, new double[] { }, false, 40, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell StormEarthAndFire = new Spell("Storm, Earth, and Fire", ClassType.Monk, ClassSpec.Windwalker, new[] { 137639, 231627 }, new[] { 27, 47 }, 0, 136038, new double[] { 0 }, new double[] { 15 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModAutoattackDamage), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.ModMaxCharges), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.OverrideActionbarSpells) });
        public Spell TouchOfDeath = new Spell("Touch of Death", ClassType.Monk, ClassSpec.Windwalker, new[] { 325215 }, new[] { 52 }, 0, 606552, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy) });
        public Spell TouchOfKarma = new Spell("Touch of Karma", ClassType.Monk, ClassSpec.Windwalker, new[] { 122470 }, new[] { 29 }, 0, 651728, new double[] { 0 }, new double[] { 10 }, false, 20, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.Dummy), new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.SchoolAbsorb), new SpellEffectData(SpellEffectName.Dummy, EffectAuraType.None) });
        public Spell Vivify = new Spell("Vivify", ClassType.Monk, ClassSpec.Windwalker, new[] { 231602 }, new[] { 37 }, 0, 1360980, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AddPctModifier) });
        public Spell WhirlingDragonPunch = new Spell("Whirling Dragon Punch", ClassType.Monk, ClassSpec.Windwalker, new[] { 152175 }, new[] { 0 }, 20, 988194, new double[] { 0 }, new double[] { 1 }, false, 0, new[] { "uncategorized" }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.PeriodicDummy), new SpellEffectData(SpellEffectName.KnockBackDest, EffectAuraType.None) });
        public Spell Windwalking = new Spell("Windwalking", ClassType.Monk, ClassSpec.Windwalker, new[] { 157411 }, new[] { 19 }, 0, 611420, new double[] { }, new double[] { }, false, 0, new string[] { }, new[] { new SpellEffectData(SpellEffectName.ApplyAura, EffectAuraType.AreaTrigger) });
    }
}