namespace WeakAuraAutomationTool.Warcraft
{
    public enum ClassSpec
    {
        Spell = 0,

        // ClassSets
        Warrior = 4,
        Paladin = 10,
        Hunter = 9,
        Rogue = 8,
        Priest = 6,
        DeathKnight = 15,
        Shaman = 11,
        Mage = 3,
        Warlock = 5,
        Monk = 53,
        Druid = 7,
        DemonHunter = 107,

        // Specializations
        Arcane = 62,
        Fire = 63,
        FrostMage = 64,
        HolyPaladin = 65,
        ProtectionPaladin = 66,
        Retribution = 70,
        Arms = 71,
        Fury = 72,
        ProtectionWarrior = 73,
        // Ferocity = 74,
        // Cunning = 79,
        // Tenacity = 81,
        Balance = 102,
        Feral = 103,
        Guardian = 104,
        RestorationDruid = 105,
        Blood = 250,
        Frost = 251,
        Unholy = 252,
        BeastMastery = 253,
        Marksmanship = 254,
        Survival = 255,
        Discipline = 256,
        HolyPriest = 257,
        Shadow = 258,
        Assassination = 259,
        Outlaw = 260,
        Subtlety = 261,
        Elemental = 262,
        Enhancement = 263,
        RestorationShaman = 264,
        Affliction = 265,
        Demonology = 266,
        Destruction = 267,
        Brewmaster = 268,
        Windwalker = 269,
        Mistweaver = 270,
        // Ferocity = 535,
        // Cunning = 536,
        // Tenacity = 537,
        Havoc = 577,
        Vengeance = 581,
        InitialWarrior = 1446,
        InitialPaladin = 1451,
        InitialHunter = 1448,
        InitialRogue = 1453,
        InitialPriest = 1452,
        InitialDeathKnight = 1455,
        InitialShaman = 1444,
        InitialMage = 1449,
        InitialWarlock = 1454,
        InitialMonk = 1450,
        InitialDruid = 1447,
        InitialDemonHunter = 1456
    }
}